//! Generated by Rutile from app/controllers/application_controller.rb. Edit the Ruby, not this file.

use rustonrails::{Request, Response, Result, json, status};

// app/controllers/application_controller.rb:6
pub fn not_found(_req: &mut Request) -> Result<Response> {
    Ok(Response::json(
        status::NOT_FOUND,
        json!({ "error": "not found" }),
    ))
}
