//! Generated by Rutile from app/controllers/comments_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Model, Request, Response, Result, errors_json,
    status,
};

use crate::models::{Comment, Post};

use super::application;

// app/controllers/comments_controller.rb:1
#[derive(Default)]
pub struct CommentsController {
    post: Option<Handle<Post>>,
}

impl Controller for CommentsController {
    fn wrap_parameters() -> Option<(&'static str, &'static [&'static str])> {
        Some((
            "comment",
            &[
                "body",
                "created_at",
                "id",
                "post_id",
                "updated_at",
                "user_id",
            ],
        ))
    }

    fn before(&mut self, req: &mut Request, _action: &str) -> Result<Option<Response>> {
        // before_action :set_post
        self.set_post(req)?;
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl CommentsController {
    // app/controllers/comments_controller.rb:4
    pub fn index(&mut self, req: &mut Request) -> Result<Response> {
        let post = self.post.ok_or(Error::Nil { what: "comments" })?;
        let comments = Post::COMMENTS
            .of(&req.ctx, post)
            .order_asc("created_at")
            .load(&mut req.ctx)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Comment>::new().render_all(&mut req.ctx, &comments)?,
        ))
    }

    // app/controllers/comments_controller.rb:8
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let post = self.post.ok_or(Error::Nil { what: "comments" })?;
        let attributes = self.comment_params(req)?;
        let comment =
            Post::COMMENTS.build(&mut req.ctx, post, Comment::from_attributes(&attributes)?)?;
        if req.ctx.save(comment)? {
            Ok(Response::json(
                status::CREATED,
                AsJson::<Comment>::new().render(&mut req.ctx, comment)?,
            ))
        } else {
            Ok(Response::json(
                status::UNPROCESSABLE_CONTENT,
                errors_json(req.ctx.errors(comment)),
            ))
        }
    }

    // app/controllers/comments_controller.rb:19
    fn set_post(&mut self, req: &mut Request) -> Result<()> {
        self.post = Some(Post::find(&mut req.ctx, req.params.value("post_id")?)?);
        Ok(())
    }

    // app/controllers/comments_controller.rb:23
    fn comment_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req.params.expect("comment", &["user_id", "body"])?)
    }
}
