//! Generated by Rutile from app/controllers/posts_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Model, Request, Response, Result, errors_json,
    status,
};

use crate::models::{Post, PostScopes, User};

use super::application;

// app/controllers/posts_controller.rb:1
#[derive(Default)]
pub struct PostsController {
    post: Option<Handle<Post>>,
}

impl Controller for PostsController {
    fn wrap_parameters() -> Option<(&'static str, Option<&'static [&'static str]>)> {
        Some((
            "post",
            Some(&[
                "body",
                "comments_count",
                "created_at",
                "id",
                "published_at",
                "status",
                "title",
                "updated_at",
                "user_id",
            ]),
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :set_post
        if matches!(action, "destroy" | "show" | "update") {
            self.set_post(req)?;
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl PostsController {
    // app/controllers/posts_controller.rb:4
    pub fn index(&mut self, req: &mut Request) -> Result<Response> {
        let posts = Post::all()
            .visible()
            .recent()
            .includes(&Post::USER)
            .limit(20);
        let records = posts.load(&mut req.ctx)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Post>::new()
                .include(&Post::USER, AsJson::<User>::new().only(&["id", "name"]))
                .render_all(&mut req.ctx, &records)?,
        ))
    }

    // app/controllers/posts_controller.rb:9
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        Ok(Response::json(
            status::OK,
            AsJson::<Post>::new().render_option(&mut req.ctx, self.post)?,
        ))
    }

    // app/controllers/posts_controller.rb:13
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let attributes = self.post_params(req)?;
        let post = req.ctx.build(Post::from_attributes(&attributes)?);
        if req.ctx.save(post)? {
            Ok(Response::json(
                status::CREATED,
                AsJson::<Post>::new().render(&mut req.ctx, post)?,
            ))
        } else {
            Ok(Response::json(
                status::UNPROCESSABLE_CONTENT,
                errors_json(req.ctx.errors(post)),
            ))
        }
    }

    // app/controllers/posts_controller.rb:22
    pub fn update(&mut self, req: &mut Request) -> Result<Response> {
        let post = self.post.ok_or(Error::Nil { what: "update" })?;
        let attributes = self.post_params(req)?;
        req.ctx.assign(post, &attributes)?;
        if req.ctx.save(post)? {
            Ok(Response::json(
                status::OK,
                AsJson::<Post>::new().render_option(&mut req.ctx, self.post)?,
            ))
        } else {
            Ok(Response::json(
                status::UNPROCESSABLE_CONTENT,
                errors_json(
                    req.ctx
                        .errors(self.post.ok_or(Error::Nil { what: "errors" })?),
                ),
            ))
        }
    }

    // app/controllers/posts_controller.rb:30
    pub fn destroy(&mut self, req: &mut Request) -> Result<Response> {
        req.ctx
            .destroy_bang(self.post.ok_or(Error::Nil { what: "destroy!" })?)?;
        Ok(Response::head(status::NO_CONTENT))
    }

    // app/controllers/posts_controller.rb:37
    fn set_post(&mut self, req: &mut Request) -> Result<()> {
        self.post = Some(Post::find(&mut req.ctx, req.params.value("id"))?);
        Ok(())
    }

    // app/controllers/posts_controller.rb:41
    fn post_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req
            .params
            .expect("post", &["user_id", "title", "body", "status"])?)
    }
}
