//! Generated by Rutile from app/controllers/users_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Model, Request, Response, Result, RubyString,
    errors_json, status,
};

use crate::models::User;

use super::application;

// app/controllers/users_controller.rb:1
#[derive(Default)]
pub struct UsersController;

impl Controller for UsersController {
    fn wrap_parameters() -> Option<(&'static str, Option<&'static [&'static str]>)> {
        Some((
            "user",
            Some(&["created_at", "email", "id", "name", "updated_at"]),
        ))
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl UsersController {
    // app/controllers/users_controller.rb:2
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        let user = User::find(&mut req.ctx, req.params.value("id")?)?;
        Ok(Response::json(
            status::OK,
            AsJson::<User>::new().render(&mut req.ctx, user)?,
        ))
    }

    // app/controllers/users_controller.rb:6
    pub fn lookup(&mut self, req: &mut Request) -> Result<Response> {
        let user = User::find_by_bang(
            &mut req.ctx,
            "email",
            req.params.value("email")?.to_s().strip().downcase(),
        )?;
        Ok(Response::json(
            status::OK,
            AsJson::<User>::new().render(&mut req.ctx, user)?,
        ))
    }

    // app/controllers/users_controller.rb:10
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let attributes = self.user_params(req)?;
        let user = req.ctx.build(User::from_attributes(&attributes)?);
        if req.ctx.save(user)? {
            Ok(Response::json(
                status::CREATED,
                AsJson::<User>::new().render(&mut req.ctx, user)?,
            ))
        } else {
            Ok(Response::json(
                status::UNPROCESSABLE_CONTENT,
                errors_json(req.ctx.errors(user)),
            ))
        }
    }

    // app/controllers/users_controller.rb:21
    fn user_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req.params.require("user")?.permit(&["name", "email"]))
    }
}
