//! Generated by Rutile from app/models/line_item.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{Behavior, BelongsTo, Check, Model, Number, Numericality, Time, model};

use super::{Order, Product};

// app/models/line_item.rb:1
model! {
pub struct LineItem in "line_items" {
id: i64,
order_id: i64,
product_id: i64,
quantity: i64,
unit_price_cents: i64,
created_at: Time,
updated_at: Time,
}
}

impl LineItem {
    // belongs_to :order
    pub const ORDER: BelongsTo<LineItem, Order> = BelongsTo::new("order", "order_id");

    // belongs_to :product
    pub const PRODUCT: BelongsTo<LineItem, Product> = BelongsTo::new("product", "product_id");
}

impl Model for LineItem {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<LineItem>> = LazyLock::new(|| {
            Behavior::<LineItem>::new()
                // belongs_to :order
                .belongs_to(&LineItem::ORDER)
                // belongs_to :product
                .belongs_to(&LineItem::PRODUCT)
                // validates :quantity, numericality
                .validates(
                    "quantity",
                    Check::Numericality(Numericality {
                        only_integer: true,
                        greater_than: Some(Number::Int(0)),
                        ..Numericality::default()
                    }),
                )
        });
        &BEHAVIOR
    }
}
