//! Generated by Rutile from app/models/order.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{
    Behavior, Check, Ctx, Error, Handle, HasMany, Model, Record, Relation, Result, RubyString,
    Time, model,
};

use super::{LineItem, Product};

// app/models/order.rb:1
model! {
pub struct Order in "orders" {
id: i64,
email: String,
status: String = "cart",
total_cents: i64,
placed_at: Time,
created_at: Time,
updated_at: Time,
}
}

impl Order {
    // has_many :line_items
    pub const LINE_ITEMS: HasMany<Order, LineItem> =
        HasMany::new("line_items", "order_id", Some(&LineItem::ORDER));

    // enum :status
    pub fn is_cart(&self) -> bool {
        self.status.as_deref() == Some("cart")
    }

    pub fn is_placed(&self) -> bool {
        self.status.as_deref() == Some("placed")
    }

    pub fn is_shipped(&self) -> bool {
        self.status.as_deref() == Some("shipped")
    }

    // normalizes :email (app/models/order.rb:6)
    pub fn normalize_email(email: String) -> String {
        email.strip().downcase()
    }

    // app/models/order.rb:10
    pub fn add_item(
        ctx: &mut Ctx,
        order: Handle<Order>,
        product: Handle<Product>,
        quantity: i64,
    ) -> Result<Handle<LineItem>> {
        let line_item = Order::LINE_ITEMS.build(ctx, order, LineItem::new_record())?;
        let price_cents = ctx[product].price_cents;
        LineItem::PRODUCT.set(ctx, line_item, product)?;
        ctx[line_item].quantity = Some(quantity);
        ctx[line_item].unit_price_cents = price_cents;
        ctx.save_bang(line_item)?;
        Ok(line_item)
    }

    // app/models/order.rb:16
    pub fn is_same_customer(
        ctx: &mut Ctx,
        order: Handle<Order>,
        other: Option<Handle<Order>>,
    ) -> Result<bool> {
        if other.is_none() {
            return Ok(false);
        }
        Ok(ctx[other.ok_or(Error::Nil { what: "email" })?]
            .email
            .clone()
            .as_deref()
            == ctx[order].email.clone().as_deref())
    }
}

impl Model for Order {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Order>> = LazyLock::new(|| {
            Behavior::<Order>::new()
                // normalizes :email
                .normalizes("email", Order::normalize_email)
                // enum :status
                .enumeration(
                    "status",
                    &[("cart", 0), ("placed", 1), ("shipped", 2)],
                    true,
                )
                // validates :email, presence
                .validates("email", Check::Presence)
                // has_many :line_items, dependent: :destroy
                .before_destroy(|ctx, order| Order::LINE_ITEMS.destroy_all(ctx, order))
        });
        &BEHAVIOR
    }
}

pub trait OrderScopes {
    fn cart(self) -> Self;
    fn not_cart(self) -> Self;
    fn not_placed(self) -> Self;
    fn not_shipped(self) -> Self;
    fn placed(self) -> Self;
    fn shipped(self) -> Self;
}

impl OrderScopes for Relation<Order> {
    fn cart(self) -> Self {
        self.where_eq("status", "cart")
    }

    fn not_cart(self) -> Self {
        self.where_not("status", "cart")
    }

    fn not_placed(self) -> Self {
        self.where_not("status", "placed")
    }

    fn not_shipped(self) -> Self {
        self.where_not("status", "shipped")
    }

    fn placed(self) -> Self {
        self.where_eq("status", "placed")
    }

    fn shipped(self) -> Self {
        self.where_eq("status", "shipped")
    }
}
