//! Generated by Rutile from app/models/order.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{
    Behavior, Check, Ctx, Error, Handle, HasMany, Model, Record, Relation, Result, RubyString,
    Time, model, sum_integers,
};

use super::{LineItem, Product};

// app/models/order.rb:1
model! {
pub struct Order in "orders" {
id: i64,
email: String,
status: String = "cart",
total_cents: i64,
placed_at: Time,
created_at: Time,
updated_at: Time,
}
}

impl Order {
    // has_many :line_items
    pub const LINE_ITEMS: HasMany<Order, LineItem> =
        HasMany::new("line_items", "order_id", Some(&LineItem::ORDER));

    // enum :status
    pub fn is_cart(&self) -> bool {
        self.status.as_deref() == Some("cart")
    }

    pub fn is_placed(&self) -> bool {
        self.status.as_deref() == Some("placed")
    }

    pub fn is_shipped(&self) -> bool {
        self.status.as_deref() == Some("shipped")
    }

    // normalizes :email (app/models/order.rb:6)
    pub fn normalize_email(email: String) -> String {
        email.strip().downcase()
    }

    // app/models/order.rb:10
    pub fn add_item(
        ctx: &mut Ctx,
        order: Handle<Order>,
        product: Handle<Product>,
        quantity: i64,
    ) -> Result<Handle<LineItem>> {
        let line_item = Order::LINE_ITEMS.build(ctx, order, LineItem::new_record())?;
        let price_cents = ctx[product].price_cents;
        LineItem::PRODUCT.set(ctx, line_item, product)?;
        ctx[line_item].quantity = Some(quantity);
        ctx[line_item].unit_price_cents = price_cents;
        ctx.save_bang(line_item)?;
        Ok(line_item)
    }

    // app/models/order.rb:15
    pub fn units(ctx: &mut Ctx, order: Handle<Order>) -> Result<i64> {
        let line_items = Order::LINE_ITEMS.of(ctx, order);
        Ok(line_items.sum::<i64>(ctx, "quantity")?)
    }

    // app/models/order.rb:20
    pub fn subtotal_cents(ctx: &mut Ctx, order: Handle<Order>) -> Result<i64> {
        let line_items = Order::LINE_ITEMS.of(ctx, order);
        let records = line_items.load(ctx)?;
        let mut mapped = Vec::with_capacity(records.len());
        for item in records {
            mapped.push(
                ctx[item].quantity.ok_or(Error::Nil { what: "*" })?
                    * ctx[item].unit_price_cents.ok_or(Error::Nil { what: "*" })?,
            );
        }
        Ok(sum_integers(0, mapped)?)
    }

    // app/models/order.rb:26
    pub fn reopen_bang(ctx: &mut Ctx, order: Handle<Order>) -> Result<()> {
        ctx.transaction_block(|ctx| {
            let line_items = Order::LINE_ITEMS.of(ctx, order);
            let records = line_items.load(ctx)?;
            for item in records {
                let product = LineItem::PRODUCT.get(ctx, item)?;
                let value = product.ok_or(Error::Nil { what: "update!" })?;
                let value_2 = ctx[product.ok_or(Error::Nil { what: "stock" })?]
                    .stock
                    .ok_or(Error::Nil { what: "+" })?
                    + ctx[item].quantity.ok_or(Error::Nil { what: "+" })?;
                ctx[value].stock = Some(value_2);
                ctx.save_bang(value)?;
            }
            ctx[order].status = Some("cart".to_string());
            ctx[order].total_cents = None;
            ctx[order].placed_at = None;
            ctx.save_bang(order)?;
            Ok(())
        })?;
        Ok(())
    }

    // app/models/order.rb:38
    pub fn is_same_customer(
        ctx: &mut Ctx,
        order: Handle<Order>,
        other: Option<Handle<Order>>,
    ) -> Result<bool> {
        if other.is_none() {
            return Ok(false);
        }
        Ok(ctx[other.ok_or(Error::Nil { what: "email" })?]
            .email
            .clone()
            .as_deref()
            == ctx[order].email.clone().as_deref())
    }
}

impl Model for Order {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Order>> = LazyLock::new(|| {
            Behavior::<Order>::new()
                // normalizes :email
                .normalizes("email", Order::normalize_email)
                // enum :status
                .enumeration(
                    "status",
                    &[("cart", 0), ("placed", 1), ("shipped", 2)],
                    true,
                )
                // validates :email, presence
                .validates("email", Check::Presence)
                // has_many :line_items, dependent: :destroy
                .before_destroy(|ctx, order| Order::LINE_ITEMS.destroy_all(ctx, order))
        });
        &BEHAVIOR
    }
}

pub trait OrderScopes {
    fn cart(self) -> Self;
    fn not_cart(self) -> Self;
    fn not_placed(self) -> Self;
    fn not_shipped(self) -> Self;
    fn placed(self) -> Self;
    fn shipped(self) -> Self;
}

impl OrderScopes for Relation<Order> {
    fn cart(self) -> Self {
        self.where_eq("status", "cart")
    }

    fn not_cart(self) -> Self {
        self.where_not("status", "cart")
    }

    fn not_placed(self) -> Self {
        self.where_not("status", "placed")
    }

    fn not_shipped(self) -> Self {
        self.where_not("status", "shipped")
    }

    fn placed(self) -> Self {
        self.where_eq("status", "placed")
    }

    fn shipped(self) -> Self {
        self.where_eq("status", "shipped")
    }
}
