//! Generated by Rutile from app/models/product.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{
    Behavior, Check, Ctx, Error, Handle, HasMany, Model, Number, Numericality, Relation, Result,
    Time, model,
};

use super::LineItem;

// app/models/product.rb:1
model! {
pub struct Product in "products" {
id: i64,
name: String,
price_cents: i64,
stock: i64 = 0,
active: bool = true,
created_at: Time,
updated_at: Time,
}
}

impl Product {
    // has_many :line_items
    pub const LINE_ITEMS: HasMany<Product, LineItem> =
        HasMany::new("line_items", "product_id", Some(&LineItem::PRODUCT));

    // app/models/product.rb:10
    pub fn is_in_stock(ctx: &mut Ctx, product: Handle<Product>, quantity: i64) -> Result<bool> {
        Ok(ctx[product].active == Some(true)
            && ctx[product].stock.ok_or(Error::Nil { what: ">=" })? >= quantity)
    }

    // app/models/product.rb:15
    pub fn price_for(ctx: &mut Ctx, product: Handle<Product>, quantity: i64) -> Result<i64> {
        Ok(ctx[product].price_cents.ok_or(Error::Nil { what: "*" })? * quantity)
    }

    // app/models/product.rb:20
    pub fn restock_bang(ctx: &mut Ctx, product: Handle<Product>, amount: i64) -> Result<()> {
        let value = ctx[product].stock.ok_or(Error::Nil { what: "+" })? + amount;
        ctx[product].stock = Some(value);
        ctx.save_bang(product)?;
        Ok(())
    }
}

impl Model for Product {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Product>> = LazyLock::new(|| {
            Behavior::<Product>::new()
                // validates :name, presence
                .validates("name", Check::Presence)
                // validates :name, uniqueness
                .validates("name", Check::Uniqueness { scope: &[] })
                // validates :price_cents, numericality
                .validates(
                    "price_cents",
                    Check::Numericality(Numericality {
                        only_integer: true,
                        greater_than_or_equal_to: Some(Number::Int(0)),
                        ..Numericality::default()
                    }),
                )
                // has_many :line_items, dependent: :destroy
                .before_destroy(|ctx, product| Product::LINE_ITEMS.destroy_all(ctx, product))
        });
        &BEHAVIOR
    }
}

pub trait ProductScopes {
    fn available(self) -> Self;
}

impl ProductScopes for Relation<Product> {
    // app/models/product.rb:7
    fn available(self) -> Self {
        self.where_eq("active", true).where_gte("stock", 1)
    }
}
