//! Generated by Rutile from app/controllers/projects_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Model, Request, Response, Result, status,
};

use crate::models::{Project, ProjectScopes, Task, User};

use super::application;

// app/controllers/projects_controller.rb:2
const PER_PAGE: i64 = 20;

// app/controllers/projects_controller.rb:1
#[derive(Default)]
pub struct ProjectsController {
    current_user: Option<Handle<User>>,
    project: Option<Handle<Project>>,
}

impl Controller for ProjectsController {
    fn wrap_parameters() -> Option<(&'static str, &'static [&'static str])> {
        Some((
            "project",
            &[
                "archived_at",
                "created_at",
                "id",
                "name",
                "owner_id",
                "updated_at",
            ],
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :authenticate (app/controllers/application_controller.rb)
        if let Some(response) = self.authenticate(req)? {
            return Ok(Some(response));
        }
        // before_action :set_project
        if matches!(action, "archive" | "destroy" | "show" | "update") {
            self.set_project(req)?;
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl ProjectsController {
    // app/controllers/projects_controller.rb:6
    pub fn index(&mut self, req: &mut Request) -> Result<Response> {
        let current_user = self.current_user.ok_or(Error::Nil { what: "projects" })?;
        let projects_2 = User::PROJECTS
            .of(&req.ctx, current_user)
            .active()
            .order_asc("name")
            .limit(PER_PAGE);
        let projects = projects_2.offset((self.page(req)? - 1) * PER_PAGE);
        let records = projects.load(&mut req.ctx)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Project>::new().render_all(&mut req.ctx, &records)?,
        ))
    }

    // app/controllers/projects_controller.rb:11
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        Ok(Response::json(
            status::OK,
            AsJson::<Project>::new()
                .include_many(
                    &Project::TASKS,
                    AsJson::<Task>::new().only(&["id", "title", "status"]),
                )
                .render(
                    &mut req.ctx,
                    self.project.ok_or(Error::Nil { what: "as_json" })?,
                )?,
        ))
    }

    // app/controllers/projects_controller.rb:15
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let current_user = self.current_user.ok_or(Error::Nil {
            what: "owned_projects",
        })?;
        let attributes = self.project_params(req)?;
        let project_2 = User::OWNED_PROJECTS.build(
            &mut req.ctx,
            current_user,
            Project::from_attributes(&attributes)?,
        )?;
        req.ctx.save_bang(project_2)?;
        let project = project_2;
        Ok(Response::json(
            status::CREATED,
            AsJson::<Project>::new().render(&mut req.ctx, project)?,
        ))
    }

    // app/controllers/projects_controller.rb:20
    pub fn update(&mut self, req: &mut Request) -> Result<Response> {
        let project = self.project.ok_or(Error::Nil { what: "update!" })?;
        let attributes = self.project_params(req)?;
        req.ctx.assign(project, &attributes)?;
        req.ctx.save_bang(project)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Project>::new().render_option(&mut req.ctx, self.project)?,
        ))
    }

    // app/controllers/projects_controller.rb:25
    pub fn destroy(&mut self, req: &mut Request) -> Result<Response> {
        req.ctx
            .destroy_bang(self.project.ok_or(Error::Nil { what: "destroy!" })?)?;
        Ok(Response::head(status::NO_CONTENT))
    }

    // app/controllers/projects_controller.rb:30
    pub fn archive(&mut self, req: &mut Request) -> Result<Response> {
        Project::archive_bang(
            &mut req.ctx,
            self.project.ok_or(Error::Nil { what: "archive!" })?,
        )?;
        Ok(Response::json(
            status::OK,
            AsJson::<Project>::new().render_option(&mut req.ctx, self.project)?,
        ))
    }

    // app/controllers/application_controller.rb:11
    fn authenticate(&mut self, req: &mut Request) -> Result<Option<Response>> {
        let header = req.header("X-Api-Token").unwrap_or_default();
        self.current_user = User::find_by(&mut req.ctx, "api_token", header)?;
        if self.current_user.is_some() {
            Ok(None)
        } else {
            Ok(Some(Response::head(401)))
        }
    }

    // app/controllers/projects_controller.rb:37
    fn set_project(&mut self, req: &mut Request) -> Result<()> {
        let current_user = self.current_user.ok_or(Error::Nil { what: "projects" })?;
        self.project = Some(
            User::PROJECTS
                .of(&req.ctx, current_user)
                .find(&mut req.ctx, req.params.value("id"))?,
        );
        Ok(())
    }

    // app/controllers/application_controller.rb:24
    fn page(&mut self, req: &mut Request) -> Result<i64> {
        Ok(i64::max(req.params.fetch("page", 1).to_i()?, 1))
    }

    // app/controllers/projects_controller.rb:41
    fn project_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req.params.expect("project", &["name"])?)
    }
}
