//! Generated by Rutile from app/controllers/tasks_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Blank, Controller, Error, Handle, Json, Model, Request, Response, Result,
    json, merge, status,
};

use crate::models::{Membership, Project, Task, TaskScopes, User};

use super::application;

// app/controllers/tasks_controller.rb:1
#[derive(Default)]
pub struct TasksController {
    current_user: Option<Handle<User>>,
    project: Option<Handle<Project>>,
    task: Option<Handle<Task>>,
}

impl Controller for TasksController {
    fn wrap_parameters() -> Option<(&'static str, Option<&'static [&'static str]>)> {
        Some((
            "task",
            Some(&[
                "assignee_id",
                "completed_at",
                "created_at",
                "due_on",
                "estimate",
                "id",
                "notes",
                "priority",
                "project_id",
                "status",
                "title",
                "updated_at",
            ]),
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :authenticate (app/controllers/application_controller.rb)
        if let Some(response) = self.authenticate(req)? {
            return Ok(Some(response));
        }
        // before_action :set_project
        if matches!(action, "create" | "index") {
            self.set_project(req)?;
        }
        // before_action :set_task
        if matches!(action, "complete" | "destroy" | "show" | "update") {
            self.set_task(req)?;
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl TasksController {
    // app/controllers/tasks_controller.rb:5
    pub fn index(&mut self, req: &mut Request) -> Result<Response> {
        let project = self.project.ok_or(Error::Nil { what: "tasks" })?;
        let mut tasks = Project::TASKS
            .of(&req.ctx, project)
            .order_asc("due_on")
            .order_asc("id");
        if req.params.value("status").is_present() {
            tasks = tasks.where_eq("status", req.params.value("status"));
        }
        if req.params.value("q").is_present() {
            tasks = tasks.search(req.params.value("q").to_str()?);
        }
        let records = tasks.load(&mut req.ctx)?;
        let mut mapped = Vec::with_capacity(records.len());
        for task in records {
            let value = AsJson::<Task>::new().render(&mut req.ctx, task)?;
            mapped.push(merge(
                value,
                json!({ "overdue": Task::is_overdue(&mut req.ctx, task)? }),
            ));
        }
        Ok(Response::json(status::OK, Json::Array(mapped)))
    }

    // app/controllers/tasks_controller.rb:12
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        Ok(Response::json(
            status::OK,
            AsJson::<Task>::new().render_option(&mut req.ctx, self.task)?,
        ))
    }

    // app/controllers/tasks_controller.rb:16
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let project = self.project.ok_or(Error::Nil { what: "tasks" })?;
        let attributes = self.task_params(req)?;
        let task_2 =
            Project::TASKS.build(&mut req.ctx, project, Task::from_attributes(&attributes)?)?;
        req.ctx.save_bang(task_2)?;
        let task = task_2;
        Ok(Response::json(
            status::CREATED,
            AsJson::<Task>::new().render(&mut req.ctx, task)?,
        ))
    }

    // app/controllers/tasks_controller.rb:21
    pub fn update(&mut self, req: &mut Request) -> Result<Response> {
        let task = self.task.ok_or(Error::Nil { what: "update!" })?;
        let attributes = self.task_params(req)?;
        req.ctx.assign(task, &attributes)?;
        req.ctx.save_bang(task)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Task>::new().render_option(&mut req.ctx, self.task)?,
        ))
    }

    // app/controllers/tasks_controller.rb:26
    pub fn destroy(&mut self, req: &mut Request) -> Result<Response> {
        req.ctx
            .destroy_bang(self.task.ok_or(Error::Nil { what: "destroy!" })?)?;
        Ok(Response::head(status::NO_CONTENT))
    }

    // app/controllers/tasks_controller.rb:31
    pub fn complete(&mut self, req: &mut Request) -> Result<Response> {
        let task = self.task.ok_or(Error::Nil { what: "done!" })?;
        req.ctx[task].status = Some("done".to_string());
        req.ctx.save_bang(task)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Task>::new().render_option(&mut req.ctx, self.task)?,
        ))
    }

    // app/controllers/application_controller.rb:11
    fn authenticate(&mut self, req: &mut Request) -> Result<Option<Response>> {
        let header = req.header("X-Api-Token").unwrap_or_default();
        self.current_user = User::find_by(&mut req.ctx, "api_token", header)?;
        if self.current_user.is_some() {
            Ok(None)
        } else {
            Ok(Some(Response::head(401)))
        }
    }

    // app/controllers/tasks_controller.rb:38
    fn set_project(&mut self, req: &mut Request) -> Result<()> {
        let current_user = self.current_user.ok_or(Error::Nil { what: "projects" })?;
        self.project = Some(
            User::PROJECTS
                .of(&req.ctx, current_user)
                .find(&mut req.ctx, req.params.value("project_id"))?,
        );
        Ok(())
    }

    // app/controllers/tasks_controller.rb:42
    fn set_task(&mut self, req: &mut Request) -> Result<()> {
        let tasks = Task::all()
            .joins(&Task::PROJECT)
            .joins(&Project::MEMBERSHIPS)
            .where_on::<Membership>(
                "user_id",
                req.ctx[self.current_user.ok_or(Error::Nil { what: "id" })?].id,
            );
        self.task = Some(tasks.find(&mut req.ctx, req.params.value("id"))?);
        Ok(())
    }

    // app/controllers/tasks_controller.rb:46
    fn task_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req.params.expect(
            "task",
            &[
                "title",
                "notes",
                "status",
                "priority",
                "estimate",
                "due_on",
                "assignee_id",
            ],
        )?)
    }
}
