//! Generated by Rutile from app/controllers/users_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Model, Request, Response, Result, status,
};

use crate::models::User;

use super::application;

// app/controllers/users_controller.rb:1
#[derive(Default)]
pub struct UsersController {
    current_user: Option<Handle<User>>,
}

impl Controller for UsersController {
    fn wrap_parameters() -> Option<(&'static str, Option<&'static [&'static str]>)> {
        Some((
            "user",
            Some(&[
                "api_token",
                "created_at",
                "email",
                "id",
                "name",
                "updated_at",
            ]),
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :authenticate (app/controllers/application_controller.rb)
        if !matches!(action, "create") {
            if let Some(response) = self.authenticate(req)? {
                return Ok(Some(response));
            }
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl UsersController {
    // app/controllers/users_controller.rb:4
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        let user = User::find(&mut req.ctx, req.params.value("id"))?;
        Ok(Response::json(
            status::OK,
            AsJson::<User>::new()
                .only(&["id", "name", "email"])
                .render(&mut req.ctx, user)?,
        ))
    }

    // app/controllers/users_controller.rb:8
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let attributes = self.user_params(req)?;
        let user_2 = req.ctx.build(User::from_attributes(&attributes)?);
        req.ctx.save_bang(user_2)?;
        let user = user_2;
        Ok(Response::json(
            status::CREATED,
            AsJson::<User>::new()
                .only(&["id", "name", "email", "api_token"])
                .render(&mut req.ctx, user)?,
        ))
    }

    // app/controllers/application_controller.rb:11
    fn authenticate(&mut self, req: &mut Request) -> Result<Option<Response>> {
        let header = req.header("X-Api-Token").unwrap_or_default();
        self.current_user = User::find_by(&mut req.ctx, "api_token", header)?;
        if self.current_user.is_some() {
            Ok(None)
        } else {
            Ok(Some(Response::head(401)))
        }
    }

    // app/controllers/users_controller.rb:15
    fn user_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req.params.expect("user", &["name", "email"])?)
    }
}
