//! Generated by Rutile from app/jobs. Edit the Ruby, not this file.

use rustonrails::jobs::JobApp;
use rustonrails::{Ctx, Json, Result};

pub mod restock_job;

/// `GlobalID.app`, and the locale and time zone Active Job records.
pub const APP: JobApp = JobApp {
    name: "store",
    locale: "en",
    timezone: "UTC",
};

/// The app's jobs by class, for the worker.
pub fn perform(ctx: &mut Ctx, class: &str, arguments: &[Json]) -> Result<bool> {
    match class {
        "RestockJob" => restock_job::perform(ctx, arguments).map(|()| true),
        _ => Ok(false),
    }
}
