//! Generated by Rutile from app/jobs/restock_job.rb. Edit the Ruby, not this file.

use rustonrails::{Ctx, Handle, Json, Result};

use crate::models::Product;

use rustonrails::jobs::{self, Job};

// app/jobs/restock_job.rb:3
pub const RESTOCK_JOB: Job = Job {
    class: "RestockJob",
    queue: "default",
};

// app/jobs/restock_job.rb:7
pub fn run(ctx: &mut Ctx, product: Handle<Product>, amount: i64) -> Result<()> {
    Product::restock_bang(ctx, product, amount)?;
    Ok(())
}

/// What a worker runs, with the arguments Active Job serialized.
pub fn perform(ctx: &mut Ctx, arguments: &[Json]) -> Result<()> {
    let product = jobs::record_at::<Product>(ctx, arguments, 0)?;
    let amount = jobs::scalar_at::<i64>(arguments, 1)?;
    run(ctx, product, amount)
}
