//! Generated by Rutile. Serves the app: `DATABASE_URL`, `BIND` (default
//! 127.0.0.1:3000) and `WORKERS` (default 5, like Puma's threads), with
//! the server's limits from `MAX_CONNECTIONS`, `IDLE_TIMEOUT`,
//! `HEADER_TIMEOUT`, `BODY_TIMEOUT`, `WRITE_TIMEOUT`, `MIN_RATE` and
//! `MAX_BODY_BYTES` (see `rustonrails::Limits`).

use rustonrails::Limits;
use rustonrails::server::{self, Config};

fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let config = Config {
        address: std::env::var("BIND").unwrap_or_else(|_| "127.0.0.1:3000".into()),
        database_url: std::env::var("DATABASE_URL").map_err(|_| "DATABASE_URL is not set")?,
        workers: std::env::var("WORKERS")
            .ok()
            .and_then(|w| w.parse().ok())
            .unwrap_or(5),
        limits: Limits::from_env()?,
    };
    let running = server::start(blog::routes::routes(), config)?;
    eprintln!("blog listening on {}", running.address);
    running.join();
    Ok(())
}
