//! Generated by Rutile from config/routes.rb. Edit the Ruby, not this file.

use rustonrails::{Blank, Request, Result, Router, ToParam, action, health, path_segment};

use crate::controllers::{CommentsController, PostsController, UsersController};

/// config/routes.rb, in the order Rails matches it.
pub fn routes() -> Router {
    Router::new()
        // GET /users/lookup(.:format) users#lookup
        .get(
            "/users/lookup(.:format)",
            action("lookup", UsersController::lookup),
        )
        .constraint(users_lookup_constraint)
        // POST /users(.:format) users#create
        .post(
            "/users(.:format)",
            action("create", UsersController::create),
        )
        // GET /users/:id(.:format) users#show
        .get(
            "/users/:id(.:format)",
            action("show", UsersController::show),
        )
        // GET /posts/:post_id/comments(.:format) comments#index
        .get(
            "/posts/:post_id/comments(.:format)",
            action("index", CommentsController::index),
        )
        // POST /posts/:post_id/comments(.:format) comments#create
        .post(
            "/posts/:post_id/comments(.:format)",
            action("create", CommentsController::create),
        )
        // GET /posts(.:format) posts#index
        .get("/posts(.:format)", action("index", PostsController::index))
        // POST /posts(.:format) posts#create
        .post(
            "/posts(.:format)",
            action("create", PostsController::create),
        )
        // GET /posts/:id(.:format) posts#show
        .get(
            "/posts/:id(.:format)",
            action("show", PostsController::show),
        )
        // PATCH /posts/:id(.:format) posts#update
        .patch(
            "/posts/:id(.:format)",
            action("update", PostsController::update),
        )
        // PUT /posts/:id(.:format) posts#update
        .put(
            "/posts/:id(.:format)",
            action("update", PostsController::update),
        )
        // DELETE /posts/:id(.:format) posts#destroy
        .delete(
            "/posts/:id(.:format)",
            action("destroy", PostsController::destroy),
        )
        // GET /up(.:format) rails/health#show
        .get("/up(.:format)", Box::new(health))
}

// config/routes.rb:3
fn users_lookup_constraint(req: &Request) -> bool {
    req.query.get("email").cloned().is_present()
}

/// `lookup_users_path`: /users/lookup(.:format)
pub fn lookup_users_path() -> Result<String> {
    Ok("/users/lookup".to_string())
}

/// `users_path`: /users(.:format)
pub fn users_path() -> Result<String> {
    Ok("/users".to_string())
}

/// `user_path`: /users/:id(.:format)
pub fn user_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/users/{}",
        path_segment(id, "users", "show", "id")?
    ))
}

/// `post_comments_path`: /posts/:post_id/comments(.:format)
pub fn post_comments_path(post_id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/posts/{}/comments",
        path_segment(post_id, "comments", "index", "post_id")?
    ))
}

/// `posts_path`: /posts(.:format)
pub fn posts_path() -> Result<String> {
    Ok("/posts".to_string())
}

/// `post_path`: /posts/:id(.:format)
pub fn post_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/posts/{}",
        path_segment(id, "posts", "show", "id")?
    ))
}

/// `rails_health_check_path`: /up(.:format)
pub fn rails_health_check_path() -> Result<String> {
    Ok("/up".to_string())
}
