//! Generated by Rutile. Serves the app: `DATABASE_URL`, `BIND` (default
//! 127.0.0.1:3000), `WORKERS` (default 5, like Puma's threads),
//! `SECRET_KEY_BASE` (the app's, for its session cookie) and `REDIS_URL`
//! (Sidekiq's, for its jobs).
//! `store work [--once]` works the jobs instead.

use rustonrails::server::{self, Config};

fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    if std::env::args().nth(1).as_deref() == Some("work") {
        let config = rustonrails::jobs::WorkerConfig {
            database_url: std::env::var("DATABASE_URL").map_err(|_| "DATABASE_URL is not set")?,
            redis_url: std::env::var("REDIS_URL").ok(),
            queues: vec!["default".into()],
            once: std::env::args().any(|arg| arg == "--once"),
        };
        rustonrails::jobs::work(config, store::jobs::perform)?;
        return Ok(());
    }
    let config = Config {
        address: std::env::var("BIND").unwrap_or_else(|_| "127.0.0.1:3000".into()),
        database_url: std::env::var("DATABASE_URL").map_err(|_| "DATABASE_URL is not set")?,
        workers: std::env::var("WORKERS")
            .ok()
            .and_then(|w| w.parse().ok())
            .unwrap_or(5),
        secret_key_base: std::env::var("SECRET_KEY_BASE").ok(),
        redis_url: std::env::var("REDIS_URL").ok(),
    };
    let running = server::start(store::routes::routes(), config)?;
    eprintln!("store listening on {}", running.address);
    running.join();
    Ok(())
}
