//! Generated by Rutile from config/routes.rb. Edit the Ruby, not this file.

use rustonrails::{Router, action, health};

use crate::controllers::{CartsController, OrdersController, ProductsController};

/// config/routes.rb, in the order Rails matches it.
pub fn routes() -> Router {
    Router::new()
        .session_store("_store_session")
        // GET /products/stats(.:format) products#stats
        .get(
            "/products/stats(.:format)",
            action("stats", ProductsController::stats),
        )
        // GET /products/low_stock(.:format) products#low_stock
        .get(
            "/products/low_stock(.:format)",
            action("low_stock", ProductsController::low_stock),
        )
        // POST /products/deactivate_sold_out(.:format) products#deactivate_sold_out
        .post(
            "/products/deactivate_sold_out(.:format)",
            action(
                "deactivate_sold_out",
                ProductsController::deactivate_sold_out,
            ),
        )
        // POST /products/restock_low(.:format) products#restock_low
        .post(
            "/products/restock_low(.:format)",
            action("restock_low", ProductsController::restock_low),
        )
        // POST /products/double(.:format) products#double
        .post(
            "/products/double(.:format)",
            action("double", ProductsController::double),
        )
        // POST /products/:id/restock(.:format) products#restock
        .post(
            "/products/:id/restock(.:format)",
            action("restock", ProductsController::restock),
        )
        // GET /products/:id/quote(.:format) products#quote
        .get(
            "/products/:id/quote(.:format)",
            action("quote", ProductsController::quote),
        )
        // GET /products/:id/availability(.:format) products#availability
        .get(
            "/products/:id/availability(.:format)",
            action("availability", ProductsController::availability),
        )
        // GET /products(.:format) products#index
        .get(
            "/products(.:format)",
            action("index", ProductsController::index),
        )
        // POST /products(.:format) products#create
        .post(
            "/products(.:format)",
            action("create", ProductsController::create),
        )
        // GET /products/:id(.:format) products#show
        .get(
            "/products/:id(.:format)",
            action("show", ProductsController::show),
        )
        // PATCH /products/:id(.:format) products#update
        .patch(
            "/products/:id(.:format)",
            action("update", ProductsController::update),
        )
        // PUT /products/:id(.:format) products#update
        .put(
            "/products/:id(.:format)",
            action("update", ProductsController::update),
        )
        // POST /orders/:id/add_item(.:format) orders#add_item
        .post(
            "/orders/:id/add_item(.:format)",
            action("add_item", OrdersController::add_item),
        )
        // POST /orders/:id/place(.:format) orders#place
        .post(
            "/orders/:id/place(.:format)",
            action("place", OrdersController::place),
        )
        // POST /orders/:id/reopen(.:format) orders#reopen
        .post(
            "/orders/:id/reopen(.:format)",
            action("reopen", OrdersController::reopen),
        )
        // GET /orders/:id/summary(.:format) orders#summary
        .get(
            "/orders/:id/summary(.:format)",
            action("summary", OrdersController::summary),
        )
        // POST /orders(.:format) orders#create
        .post(
            "/orders(.:format)",
            action("create", OrdersController::create),
        )
        // GET /orders/:id(.:format) orders#show
        .get(
            "/orders/:id(.:format)",
            action("show", OrdersController::show),
        )
        // POST /cart/add(.:format) carts#add
        .post("/cart/add(.:format)", action("add", CartsController::add))
        // DELETE /cart/clear(.:format) carts#clear
        .delete(
            "/cart/clear(.:format)",
            action("clear", CartsController::clear),
        )
        // GET /cart(.:format) carts#show
        .get("/cart(.:format)", action("show", CartsController::show))
        // GET /up(.:format) rails/health#show
        .get("/up(.:format)", Box::new(health))
}
