//! Generated by Rutile from config/routes.rb. Edit the Ruby, not this file.

use rustonrails::{Result, Router, ToParam, action, health, path_segment};

use crate::controllers::{
    CartsController, OrdersController, ProductsController, StorefrontController,
};

/// config/routes.rb, in the order Rails matches it.
pub fn routes() -> Router {
    Router::new()
        .session_store("_store_session")
        .default_headers(&[
            ("X-Frame-Options", "SAMEORIGIN"),
            ("X-XSS-Protection", "0"),
            ("X-Content-Type-Options", "nosniff"),
            ("X-Permitted-Cross-Domain-Policies", "none"),
            ("Referrer-Policy", "strict-origin-when-cross-origin"),
        ])
        // GET /products/stats(.:format) products#stats
        .get(
            "/products/stats(.:format)",
            action("stats", ProductsController::stats),
        )
        // GET /products/low_stock(.:format) products#low_stock
        .get(
            "/products/low_stock(.:format)",
            action("low_stock", ProductsController::low_stock),
        )
        // POST /products/deactivate_sold_out(.:format) products#deactivate_sold_out
        .post(
            "/products/deactivate_sold_out(.:format)",
            action(
                "deactivate_sold_out",
                ProductsController::deactivate_sold_out,
            ),
        )
        // POST /products/restock_low(.:format) products#restock_low
        .post(
            "/products/restock_low(.:format)",
            action("restock_low", ProductsController::restock_low),
        )
        // POST /products/double(.:format) products#double
        .post(
            "/products/double(.:format)",
            action("double", ProductsController::double),
        )
        // POST /products/:id/restock(.:format) products#restock
        .post(
            "/products/:id/restock(.:format)",
            action("restock", ProductsController::restock),
        )
        // POST /products/:id/restock_later(.:format) products#restock_later
        .post(
            "/products/:id/restock_later(.:format)",
            action("restock_later", ProductsController::restock_later),
        )
        // GET /products/:id/quote(.:format) products#quote
        .get(
            "/products/:id/quote(.:format)",
            action("quote", ProductsController::quote),
        )
        // GET /products/:id/availability(.:format) products#availability
        .get(
            "/products/:id/availability(.:format)",
            action("availability", ProductsController::availability),
        )
        // GET /products(.:format) products#index
        .get(
            "/products(.:format)",
            action("index", ProductsController::index),
        )
        // POST /products(.:format) products#create
        .post(
            "/products(.:format)",
            action("create", ProductsController::create),
        )
        // GET /products/:id(.:format) products#show
        .get(
            "/products/:id(.:format)",
            action("show", ProductsController::show),
        )
        // PATCH /products/:id(.:format) products#update
        .patch(
            "/products/:id(.:format)",
            action("update", ProductsController::update),
        )
        // PUT /products/:id(.:format) products#update
        .put(
            "/products/:id(.:format)",
            action("update", ProductsController::update),
        )
        // POST /orders/:id/add_item(.:format) orders#add_item
        .post(
            "/orders/:id/add_item(.:format)",
            action("add_item", OrdersController::add_item),
        )
        // POST /orders/:id/place(.:format) orders#place
        .post(
            "/orders/:id/place(.:format)",
            action("place", OrdersController::place),
        )
        // POST /orders/:id/reopen(.:format) orders#reopen
        .post(
            "/orders/:id/reopen(.:format)",
            action("reopen", OrdersController::reopen),
        )
        // GET /orders/:id/summary(.:format) orders#summary
        .get(
            "/orders/:id/summary(.:format)",
            action("summary", OrdersController::summary),
        )
        // POST /orders(.:format) orders#create
        .post(
            "/orders(.:format)",
            action("create", OrdersController::create),
        )
        // GET /orders/:id(.:format) orders#show
        .get(
            "/orders/:id(.:format)",
            action("show", OrdersController::show),
        )
        // POST /cart/add(.:format) carts#add
        .post("/cart/add(.:format)", action("add", CartsController::add))
        // DELETE /cart/clear(.:format) carts#clear
        .delete(
            "/cart/clear(.:format)",
            action("clear", CartsController::clear),
        )
        // GET /cart(.:format) carts#show
        .get("/cart(.:format)", action("show", CartsController::show))
        // GET /shop(.:format) storefront#index
        .get(
            "/shop(.:format)",
            action("index", StorefrontController::index),
        )
        // GET /shop/:id(.:format) storefront#show
        .get(
            "/shop/:id(.:format)",
            action("show", StorefrontController::show),
        )
        // GET /up(.:format) rails/health#show
        .get("/up(.:format)", Box::new(health))
}

/// `stats_products_path`: /products/stats(.:format)
pub fn stats_products_path() -> Result<String> {
    Ok("/products/stats".to_string())
}

/// `low_stock_products_path`: /products/low_stock(.:format)
pub fn low_stock_products_path() -> Result<String> {
    Ok("/products/low_stock".to_string())
}

/// `deactivate_sold_out_products_path`: /products/deactivate_sold_out(.:format)
pub fn deactivate_sold_out_products_path() -> Result<String> {
    Ok("/products/deactivate_sold_out".to_string())
}

/// `restock_low_products_path`: /products/restock_low(.:format)
pub fn restock_low_products_path() -> Result<String> {
    Ok("/products/restock_low".to_string())
}

/// `double_products_path`: /products/double(.:format)
pub fn double_products_path() -> Result<String> {
    Ok("/products/double".to_string())
}

/// `restock_product_path`: /products/:id/restock(.:format)
pub fn restock_product_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/products/{}/restock",
        path_segment(id, "products", "restock", "id")?
    ))
}

/// `restock_later_product_path`: /products/:id/restock_later(.:format)
pub fn restock_later_product_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/products/{}/restock_later",
        path_segment(id, "products", "restock_later", "id")?
    ))
}

/// `quote_product_path`: /products/:id/quote(.:format)
pub fn quote_product_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/products/{}/quote",
        path_segment(id, "products", "quote", "id")?
    ))
}

/// `availability_product_path`: /products/:id/availability(.:format)
pub fn availability_product_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/products/{}/availability",
        path_segment(id, "products", "availability", "id")?
    ))
}

/// `products_path`: /products(.:format)
pub fn products_path() -> Result<String> {
    Ok("/products".to_string())
}

/// `product_path`: /products/:id(.:format)
pub fn product_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/products/{}",
        path_segment(id, "products", "show", "id")?
    ))
}

/// `add_item_order_path`: /orders/:id/add_item(.:format)
pub fn add_item_order_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/orders/{}/add_item",
        path_segment(id, "orders", "add_item", "id")?
    ))
}

/// `place_order_path`: /orders/:id/place(.:format)
pub fn place_order_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/orders/{}/place",
        path_segment(id, "orders", "place", "id")?
    ))
}

/// `reopen_order_path`: /orders/:id/reopen(.:format)
pub fn reopen_order_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/orders/{}/reopen",
        path_segment(id, "orders", "reopen", "id")?
    ))
}

/// `summary_order_path`: /orders/:id/summary(.:format)
pub fn summary_order_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/orders/{}/summary",
        path_segment(id, "orders", "summary", "id")?
    ))
}

/// `orders_path`: /orders(.:format)
pub fn orders_path() -> Result<String> {
    Ok("/orders".to_string())
}

/// `order_path`: /orders/:id(.:format)
pub fn order_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/orders/{}",
        path_segment(id, "orders", "show", "id")?
    ))
}

/// `add_cart_path`: /cart/add(.:format)
pub fn add_cart_path() -> Result<String> {
    Ok("/cart/add".to_string())
}

/// `clear_cart_path`: /cart/clear(.:format)
pub fn clear_cart_path() -> Result<String> {
    Ok("/cart/clear".to_string())
}

/// `cart_path`: /cart(.:format)
pub fn cart_path() -> Result<String> {
    Ok("/cart".to_string())
}

/// `shop_path`: /shop(.:format)
pub fn shop_path() -> Result<String> {
    Ok("/shop".to_string())
}

/// `shop_product_path`: /shop/:id(.:format)
pub fn shop_product_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/shop/{}",
        path_segment(id, "storefront", "show", "id")?
    ))
}

/// `rails_health_check_path`: /up(.:format)
pub fn rails_health_check_path() -> Result<String> {
    Ok("/up".to_string())
}
