//! Generated by Rutile from config/routes.rb. Edit the Ruby, not this file.

use rustonrails::{Router, action, health};

use crate::controllers::{OrdersController, ProductsController};

/// config/routes.rb, in the order Rails matches it.
pub fn routes() -> Router {
    Router::new()
        // POST /products/:id/restock(.:format) products#restock
        .post(
            "/products/:id/restock(.:format)",
            action("restock", ProductsController::restock),
        )
        // GET /products/:id/quote(.:format) products#quote
        .get(
            "/products/:id/quote(.:format)",
            action("quote", ProductsController::quote),
        )
        // GET /products(.:format) products#index
        .get(
            "/products(.:format)",
            action("index", ProductsController::index),
        )
        // POST /products(.:format) products#create
        .post(
            "/products(.:format)",
            action("create", ProductsController::create),
        )
        // GET /products/:id(.:format) products#show
        .get(
            "/products/:id(.:format)",
            action("show", ProductsController::show),
        )
        // PATCH /products/:id(.:format) products#update
        .patch(
            "/products/:id(.:format)",
            action("update", ProductsController::update),
        )
        // PUT /products/:id(.:format) products#update
        .put(
            "/products/:id(.:format)",
            action("update", ProductsController::update),
        )
        // POST /orders/:id/add_item(.:format) orders#add_item
        .post(
            "/orders/:id/add_item(.:format)",
            action("add_item", OrdersController::add_item),
        )
        // POST /orders(.:format) orders#create
        .post(
            "/orders(.:format)",
            action("create", OrdersController::create),
        )
        // GET /orders/:id(.:format) orders#show
        .get(
            "/orders/:id(.:format)",
            action("show", OrdersController::show),
        )
        // GET /up(.:format) rails/health#show
        .get("/up(.:format)", Box::new(health))
}
