//! Generated by Rutile from app/controllers/application_controller.rb. Edit the Ruby, not this file.

use rustonrails::{RecordInvalid, Request, Response, Result, errors_json, json, status};

// app/controllers/application_controller.rb:7
pub fn not_found(_req: &mut Request) -> Result<Response> {
    Ok(Response::json(
        status::NOT_FOUND,
        json!({ "error": "not found" }),
    ))
}

// app/controllers/application_controller.rb:11
pub fn invalid(_req: &mut Request, error: RecordInvalid) -> Result<Response> {
    Ok(Response::json(
        status::UNPROCESSABLE_CONTENT,
        errors_json(&error.errors),
    ))
}
