//! Generated by Rutile from app/controllers/carts_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    Blank, Controller, Error, Model, Request, Response, Result, Value, json, status, value_json,
};

use crate::models::Product;

use super::application;

// app/controllers/carts_controller.rb:2
#[derive(Default)]
pub struct CartsController;

impl Controller for CartsController {
    fn wrap_parameters() -> Option<(&'static str, Option<&'static [&'static str]>)> {
        Some(("cart", None))
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl CartsController {
    // app/controllers/carts_controller.rb:5
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        let product_id = value_json(req.session.get("product_id")?);
        let value = req.session.get("quantity")?.to_i()?;
        let shopper = value_json(req.session.get("shopper")?);
        Ok(Response::json(
            status::OK,
            json!({ "product_id": product_id, "quantity": value, "shopper": shopper, "visits": Value::from(req.cookies.get("visits")).to_i()? }),
        ))
    }

    // app/controllers/carts_controller.rb:10
    pub fn add(&mut self, req: &mut Request) -> Result<Response> {
        let product = Product::find(&mut req.ctx, req.params.value("product_id")?)?;
        let value = req.session.get("product_id")?;
        let quantity = if value.equals(&Value::from(req.ctx[product].id)) {
            req.session.get("quantity")?.to_i()?
        } else {
            0
        };
        let id = req.ctx[product].id;
        req.session.set("product_id", Value::from(id))?;
        req.session.set(
            "quantity",
            Value::Int(quantity + req.params.fetch("quantity", 1)?.to_i()?),
        )?;
        if req.params.value("shopper")?.is_present() {
            req.session.set("shopper", req.params.value("shopper")?)?;
        }
        let value_2 = (Value::from(req.cookies.get("visits")).to_i()? + 1).to_string();
        req.cookies.set("visits", value_2);
        let id_2 = req.ctx[product].id;
        Ok(Response::json(
            status::OK,
            json!({ "product_id": id_2, "quantity": value_json(req.session.get("quantity")?) }),
        ))
    }

    // app/controllers/carts_controller.rb:20
    pub fn clear(&mut self, req: &mut Request) -> Result<Response> {
        req.session.reset()?;
        Ok(Response::head(status::NO_CONTENT))
    }
}
