//! Generated by Rutile from app/controllers/orders_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Model, Request, Response, Result, status,
};

use crate::models::{LineItem, Order, Product};

use super::application;

// app/controllers/orders_controller.rb:1
#[derive(Default)]
pub struct OrdersController {
    order: Option<Handle<Order>>,
}

impl Controller for OrdersController {
    fn wrap_parameters() -> Option<(&'static str, &'static [&'static str])> {
        Some((
            "order",
            &[
                "created_at",
                "email",
                "id",
                "placed_at",
                "status",
                "total_cents",
                "updated_at",
            ],
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :set_order
        if matches!(action, "add_item" | "show") {
            self.set_order(req)?;
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl OrdersController {
    // app/controllers/orders_controller.rb:4
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        Ok(Response::json(
            status::OK,
            AsJson::<Order>::new()
                .include_many(
                    &Order::LINE_ITEMS,
                    AsJson::<LineItem>::new().only(&[
                        "id",
                        "product_id",
                        "quantity",
                        "unit_price_cents",
                    ]),
                )
                .render(
                    &mut req.ctx,
                    self.order.ok_or(Error::Nil { what: "as_json" })?,
                )?,
        ))
    }

    // app/controllers/orders_controller.rb:8
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let attributes = self.order_params(req)?;
        let order_2 = req.ctx.build(Order::from_attributes(&attributes)?);
        req.ctx.save_bang(order_2)?;
        let order = order_2;
        Ok(Response::json(
            status::CREATED,
            AsJson::<Order>::new().render(&mut req.ctx, order)?,
        ))
    }

    // app/controllers/orders_controller.rb:13
    pub fn add_item(&mut self, req: &mut Request) -> Result<Response> {
        let product = Product::find(&mut req.ctx, req.params.value("product_id"))?;
        let item = Order::add_item(
            &mut req.ctx,
            self.order.ok_or(Error::Nil { what: "add_item" })?,
            product,
            req.params.fetch("quantity", 1).to_i()?,
        )?;
        Ok(Response::json(
            status::CREATED,
            AsJson::<LineItem>::new().render(&mut req.ctx, item)?,
        ))
    }

    // app/controllers/orders_controller.rb:21
    fn set_order(&mut self, req: &mut Request) -> Result<()> {
        self.order = Some(Order::find(&mut req.ctx, req.params.value("id"))?);
        Ok(())
    }

    // app/controllers/orders_controller.rb:25
    fn order_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req.params.expect("order", &["email"])?)
    }
}
