//! Generated by Rutile from app/controllers/orders_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Model, Request, Response, Result, json, now,
    status,
};

use crate::models::{LineItem, Order, Product};

use super::application;

// app/controllers/orders_controller.rb:1
#[derive(Default)]
pub struct OrdersController {
    order: Option<Handle<Order>>,
}

impl Controller for OrdersController {
    fn wrap_parameters() -> Option<(&'static str, &'static [&'static str])> {
        Some((
            "order",
            &[
                "created_at",
                "email",
                "id",
                "placed_at",
                "status",
                "total_cents",
                "updated_at",
            ],
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :set_order
        if matches!(action, "add_item" | "place" | "reopen" | "show" | "summary") {
            self.set_order(req)?;
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl OrdersController {
    // app/controllers/orders_controller.rb:4
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        Ok(Response::json(
            status::OK,
            AsJson::<Order>::new()
                .include_many(
                    &Order::LINE_ITEMS,
                    AsJson::<LineItem>::new().only(&[
                        "id",
                        "product_id",
                        "quantity",
                        "unit_price_cents",
                    ]),
                )
                .render(
                    &mut req.ctx,
                    self.order.ok_or(Error::Nil { what: "as_json" })?,
                )?,
        ))
    }

    // app/controllers/orders_controller.rb:8
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let attributes = self.order_params(req)?;
        let order_2 = req.ctx.build(Order::from_attributes(&attributes)?);
        req.ctx.save_bang(order_2)?;
        let order = order_2;
        Ok(Response::json(
            status::CREATED,
            AsJson::<Order>::new().render(&mut req.ctx, order)?,
        ))
    }

    // app/controllers/orders_controller.rb:13
    pub fn add_item(&mut self, req: &mut Request) -> Result<Response> {
        let product = Product::find(&mut req.ctx, req.params.value("product_id")?)?;
        let item = Order::add_item(
            &mut req.ctx,
            self.order.ok_or(Error::Nil { what: "add_item" })?,
            product,
            req.params.fetch("quantity", 1)?.to_i()?,
        )?;
        Ok(Response::json(
            status::CREATED,
            AsJson::<LineItem>::new().render(&mut req.ctx, item)?,
        ))
    }

    // app/controllers/orders_controller.rb:21
    pub fn place(&mut self, req: &mut Request) -> Result<Response> {
        let mut total = 0;
        let placed = req.transaction_block(|req| {
            let order = self.order.ok_or(Error::Nil { what: "line_items" })?;
            let line_items = Order::LINE_ITEMS.of(&req.ctx, order);
            let records = line_items.load(&mut req.ctx)?;
            for item in records {
                let product = LineItem::PRODUCT.get(&mut req.ctx, item)?;
                if req.ctx[product.ok_or(Error::Nil { what: "stock" })?]
                    .stock
                    .ok_or(Error::Nil { what: "<" })?
                    < req.ctx[item].quantity.ok_or(Error::Nil { what: "<" })?
                {
                    return Err(Error::Rollback);
                }
                let value = product.ok_or(Error::Nil { what: "update!" })?;
                let value_2 = req.ctx[product.ok_or(Error::Nil { what: "stock" })?]
                    .stock
                    .ok_or(Error::Nil { what: "-" })?
                    - req.ctx[item].quantity.ok_or(Error::Nil { what: "-" })?;
                req.ctx[value].stock = Some(value_2);
                req.ctx.save_bang(value)?;
                total = total
                    + req.ctx[item].quantity.ok_or(Error::Nil { what: "*" })?
                        * req.ctx[item]
                            .unit_price_cents
                            .ok_or(Error::Nil { what: "*" })?;
            }
            let order_2 = self.order.ok_or(Error::Nil { what: "update!" })?;
            req.ctx[order_2].status = Some("placed".to_string());
            req.ctx[order_2].total_cents = Some(total);
            req.ctx[order_2].placed_at = Some(now());
            req.ctx.save_bang(order_2)?;
            Ok(true)
        })?;
        if placed == Some(true) {
            Ok(Response::json(
                status::OK,
                AsJson::<Order>::new().render_option(&mut req.ctx, self.order)?,
            ))
        } else {
            Ok(Response::json(
                status::UNPROCESSABLE_CONTENT,
                json!({ "error": "not enough stock" }),
            ))
        }
    }

    // app/controllers/orders_controller.rb:41
    pub fn reopen(&mut self, req: &mut Request) -> Result<Response> {
        Order::reopen_bang(
            &mut req.ctx,
            self.order.ok_or(Error::Nil { what: "reopen!" })?,
        )?;
        Ok(Response::json(
            status::OK,
            AsJson::<Order>::new().render_option(&mut req.ctx, self.order)?,
        ))
    }

    // app/controllers/orders_controller.rb:46
    pub fn summary(&mut self, req: &mut Request) -> Result<Response> {
        let units = Order::units(
            &mut req.ctx,
            self.order.ok_or(Error::Nil { what: "units" })?,
        )?;
        let subtotal_cents = Order::subtotal_cents(
            &mut req.ctx,
            self.order.ok_or(Error::Nil {
                what: "subtotal_cents",
            })?,
        )?;
        let order = self.order.ok_or(Error::Nil { what: "line_items" })?;
        let line_items = Order::LINE_ITEMS.of(&req.ctx, order);
        let count = line_items.count(&mut req.ctx)?;
        Ok(Response::json(
            status::OK,
            json!({ "units": units, "subtotal_cents": subtotal_cents, "lines": count, "placed": req.ctx[self.order.ok_or(Error::Nil { what: "placed?" })?].is_placed() }),
        ))
    }

    // app/controllers/orders_controller.rb:53
    fn set_order(&mut self, req: &mut Request) -> Result<()> {
        self.order = Some(Order::find(&mut req.ctx, req.params.value("id")?)?);
        Ok(())
    }

    // app/controllers/orders_controller.rb:57
    fn order_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req.params.expect("order", &["email"])?)
    }
}
