//! Generated by Rutile from app/controllers/products_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Json, Model, Request, Response, Result, Value,
    div_integers, json, status, sum_floats, sum_integers, value_json,
};

use crate::models::{Product, ProductScopes};

use super::application;

// app/controllers/products_controller.rb:1
#[derive(Default)]
pub struct ProductsController {
    product: Option<Handle<Product>>,
}

impl Controller for ProductsController {
    fn wrap_parameters() -> Option<(&'static str, Option<&'static [&'static str]>)> {
        Some((
            "product",
            Some(&[
                "active",
                "created_at",
                "id",
                "name",
                "price_cents",
                "stock",
                "updated_at",
            ]),
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :set_product
        if matches!(
            action,
            "availability" | "quote" | "restock" | "restock_later" | "show" | "update"
        ) {
            self.set_product(req)?;
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl ProductsController {
    // app/controllers/products_controller.rb:4
    pub fn index(&mut self, req: &mut Request) -> Result<Response> {
        let products = Product::all()
            .available()
            .order_asc("name")
            .load(&mut req.ctx)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_all(&mut req.ctx, &products)?,
        ))
    }

    // app/controllers/products_controller.rb:8
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_option(&mut req.ctx, self.product)?,
        ))
    }

    // app/controllers/products_controller.rb:12
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let attributes = self.product_params(req)?;
        let product_2 = req.ctx.build(Product::from_attributes(&attributes)?);
        req.ctx.save_bang(product_2)?;
        let product = product_2;
        Ok(Response::json(
            status::CREATED,
            AsJson::<Product>::new().render(&mut req.ctx, product)?,
        ))
    }

    // app/controllers/products_controller.rb:17
    pub fn update(&mut self, req: &mut Request) -> Result<Response> {
        let product = self.product.ok_or(Error::Nil { what: "update!" })?;
        let attributes = self.product_params(req)?;
        req.ctx.assign(product, &attributes)?;
        req.ctx.save_bang(product)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_option(&mut req.ctx, self.product)?,
        ))
    }

    // app/controllers/products_controller.rb:22
    pub fn restock(&mut self, req: &mut Request) -> Result<Response> {
        let product = self.product.ok_or(Error::Nil { what: "restock!" })?;
        let amount = req.params.fetch("amount", 0)?.to_i()?;
        let amount_2 = self.amount(req, amount)?;
        Product::restock_bang(&mut req.ctx, product, amount_2)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_option(&mut req.ctx, self.product)?,
        ))
    }

    // app/controllers/products_controller.rb:28
    pub fn stats(&mut self, req: &mut Request) -> Result<Response> {
        let count = Product::all().count(&mut req.ctx)?;
        let size = Product::all().where_eq("active", true).size(&mut req.ctx)?;
        let stock = Product::all().sum::<i64>(&mut req.ctx, "stock")?;
        let price_cents = Product::all().minimum::<i64>(&mut req.ctx, "price_cents")?;
        let price_cents_2 = Product::all().maximum::<i64>(&mut req.ctx, "price_cents")?;
        let name = Product::all().minimum::<String>(&mut req.ctx, "name")?;
        let names = Json::from(
            Product::all()
                .order_asc("name")
                .pluck_present::<String>(&mut req.ctx, "name")?,
        );
        let stock_2 = Product::all()
            .order_asc("name")
            .limit(2)
            .sum::<i64>(&mut req.ctx, "stock")?;
        let count_2 = Product::all()
            .order_asc("name")
            .limit(2)
            .count(&mut req.ctx)?;
        let sold_out = Product::all().where_eq("stock", 0).exists(&mut req.ctx)?;
        let all_active = !Product::all()
            .where_eq("active", false)
            .is_any(&mut req.ctx)?;
        let product = Product::all()
            .order_asc("price_cents")
            .first(&mut req.ctx)?;
        Ok(Response::json(
            status::OK,
            json!({ "count": count, "active": size, "units": stock, "cheapest_cents": price_cents, "priciest_cents": price_cents_2, "first_name": name, "names": names, "units_of_two": stock_2, "count_of_two": count_2, "sold_out": sold_out, "all_active": all_active, "cheapest": product.and_then(|product| req.ctx[product].name.clone()) }),
        ))
    }

    // app/controllers/products_controller.rb:47
    pub fn low_stock(&mut self, req: &mut Request) -> Result<Response> {
        let below = req.params.fetch("below", 5)?.to_i()?;
        let records = Product::all().order_asc("name").load(&mut req.ctx)?;
        let mut selected = Vec::new();
        for product in records {
            if req.ctx[product].stock.ok_or(Error::Nil { what: "<" })? < below {
                selected.push(product);
            }
        }
        let low = selected;
        let mut mapped = Vec::with_capacity(low.len());
        for product_2 in low.clone() {
            mapped.push(req.ctx[product_2].name.clone());
        }
        let mut mapped_2 = Vec::with_capacity(low.len());
        for product_3 in low.clone() {
            mapped_2.push(req.ctx[product_3].stock);
        }
        let units = sum_integers(0, mapped_2)?;
        let mut mapped_3 = Vec::with_capacity(low.len());
        for product_4 in low.clone() {
            mapped_3.push(
                req.ctx[product_4]
                    .price_cents
                    .ok_or(Error::Nil { what: "*" })?
                    * req.ctx[product_4].stock.ok_or(Error::Nil { what: "*" })?,
            );
        }
        let value_cents = sum_integers(0, mapped_3)?;
        let mut kept = Vec::new();
        for product_5 in low.clone() {
            if !(req.ctx[product_5].active == Some(true)) {
                kept.push(product_5);
            }
        }
        let mut mapped_4 = Vec::with_capacity(low.len());
        for product_6 in low.clone() {
            mapped_4.push(req.ctx[product_6].price_cents);
        }
        Ok(Response::json(
            status::OK,
            json!({ "names": Json::from(mapped), "units": units, "value_cents": value_cents, "inactive": (kept.len() as i64), "price_cents": sum_floats(0.0, mapped_4.into_iter().map(|item| item.map(|item| item as f64)))? }),
        ))
    }

    // app/controllers/products_controller.rb:62
    pub fn restock_low(&mut self, req: &mut Request) -> Result<Response> {
        let low = Product::all()
            .where_eq("active", true)
            .where_sql("stock < ?", vec![5.into()]);
        let records = low.load(&mut req.ctx)?;
        for product in records {
            let value = req.ctx[product].stock.ok_or(Error::Nil { what: "+" })? + 10;
            req.ctx[product].stock = Some(value);
            req.ctx.save_bang(product)?;
        }
        let size = low.size(&mut req.ctx)?;
        let any = low.is_any(&mut req.ctx)?;
        let records_2 = low.load(&mut req.ctx)?;
        let mut mapped = Vec::with_capacity(records_2.len());
        for product_2 in records_2 {
            mapped.push(req.ctx[product_2].name.clone());
        }
        let product_3 = low.first(&mut req.ctx)?;
        let first = product_3.and_then(|product| req.ctx[product].name.clone());
        Ok(Response::json(
            status::OK,
            json!({ "restocked": size, "any": any, "names": Json::from(mapped), "first": first, "still_low": low.count(&mut req.ctx)? }),
        ))
    }

    // app/controllers/products_controller.rb:69
    pub fn deactivate_sold_out(&mut self, req: &mut Request) -> Result<Response> {
        let mut deactivated = 0;
        let mut batches = Product::all().where_eq("active", true).batches(2);
        while let Some(batch) = batches.next(&mut req.ctx)? {
            for product in batch {
                if req.ctx[product].stock == Some(0) {
                    req.ctx[product].active = Some(false);
                    req.ctx.save_bang(product)?;
                    deactivated = deactivated + 1;
                }
            }
        }
        Ok(Response::json(
            status::OK,
            json!({ "deactivated": deactivated, "active": Json::from(Product::all().where_eq("active", true).order_asc("name").pluck_present::<String>(&mut req.ctx, "name")?) }),
        ))
    }

    // app/controllers/products_controller.rb:82
    pub fn double(&mut self, req: &mut Request) -> Result<Response> {
        let value = req.params.fetch("value", 1)?;
        Ok(Response::json(
            status::OK,
            json!({ "value": value_json(value.clone()), "doubled": value_json(value.mul(&Value::Int(2))?), "half": div_integers(value.to_i()?, 2)?, "text": format!("got {}", value.to_s()) }),
        ))
    }

    // app/controllers/products_controller.rb:87
    pub fn availability(&mut self, req: &mut Request) -> Result<Response> {
        let id = req.ctx[self.product.ok_or(Error::Nil { what: "id" })?].id;
        let availability = value_json(Product::availability(
            &mut req.ctx,
            self.product.ok_or(Error::Nil {
                what: "availability",
            })?,
        )?);
        Ok(Response::json(
            status::OK,
            json!({ "id": id, "availability": availability, "tagged": value_json(Product::tag_with(&mut req.ctx, self.product.ok_or(Error::Nil { what: "tag_with" })?, req.params.value("tag")?)?) }),
        ))
    }

    // app/controllers/products_controller.rb:92
    pub fn restock_later(&mut self, req: &mut Request) -> Result<Response> {
        let product = self.product;
        let amount = req.params.fetch("amount", 1)?.to_i()?;
        let amount_2 = self.amount(req, amount)?;
        crate::jobs::restock_job::RESTOCK_JOB.perform_later(
            &crate::jobs::APP,
            vec![
                rustonrails::jobs::record_argument(&req.ctx, &crate::jobs::APP, product)?,
                Json::from(amount_2),
            ],
        )?;
        Ok(Response::json(202, json!({ "queued": true })))
    }

    // app/controllers/products_controller.rb:97
    pub fn quote(&mut self, req: &mut Request) -> Result<Response> {
        let quantity_2 = req.params.fetch("quantity", 1)?.to_i()?;
        let quantity = self.amount(req, quantity_2)?;
        let id = req.ctx[self.product.ok_or(Error::Nil { what: "id" })?].id;
        let price_for = Product::price_for(
            &mut req.ctx,
            self.product.ok_or(Error::Nil { what: "price_for" })?,
            quantity,
        )?;
        Ok(Response::json(
            status::OK,
            json!({ "product_id": id, "quantity": quantity, "total_cents": price_for, "in_stock": Product::is_in_stock(&mut req.ctx, self.product.ok_or(Error::Nil { what: "in_stock?" })?, quantity)? }),
        ))
    }

    // app/controllers/products_controller.rb:105
    fn set_product(&mut self, req: &mut Request) -> Result<()> {
        self.product = Some(Product::find(&mut req.ctx, req.params.value("id")?)?);
        Ok(())
    }

    // app/controllers/products_controller.rb:109
    fn product_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req
            .params
            .expect("product", &["name", "price_cents", "stock", "active"])?)
    }

    // app/controllers/products_controller.rb:115
    fn amount(&mut self, _req: &mut Request, requested: i64) -> Result<i64> {
        Ok(i64::max(requested, 0))
    }
}
