//! Generated by Rutile from app/controllers/products_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    AsJson, Attributes, Controller, Error, Handle, Model, Request, Response, Result, json, status,
};

use crate::models::{Product, ProductScopes};

use super::application;

// app/controllers/products_controller.rb:1
#[derive(Default)]
pub struct ProductsController {
    product: Option<Handle<Product>>,
}

impl Controller for ProductsController {
    fn wrap_parameters() -> Option<(&'static str, &'static [&'static str])> {
        Some((
            "product",
            &[
                "active",
                "created_at",
                "id",
                "name",
                "price_cents",
                "stock",
                "updated_at",
            ],
        ))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // before_action :set_product
        if matches!(action, "quote" | "restock" | "show" | "update") {
            self.set_product(req)?;
        }
        Ok(None)
    }

    fn rescue(&mut self, req: &mut Request, error: Error) -> Result<Response> {
        match error {
            // rescue_from ActiveRecord::RecordInvalid, with: :invalid
            Error::RecordInvalid(error) => application::invalid(req, error),
            // rescue_from ActiveRecord::RecordNotFound, with: :not_found
            Error::RecordNotFound { .. } => application::not_found(req),
            other => Err(other),
        }
    }
}

impl ProductsController {
    // app/controllers/products_controller.rb:4
    pub fn index(&mut self, req: &mut Request) -> Result<Response> {
        let products = Product::all()
            .available()
            .order_asc("name")
            .load(&mut req.ctx)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_all(&mut req.ctx, &products)?,
        ))
    }

    // app/controllers/products_controller.rb:8
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_option(&mut req.ctx, self.product)?,
        ))
    }

    // app/controllers/products_controller.rb:12
    pub fn create(&mut self, req: &mut Request) -> Result<Response> {
        let attributes = self.product_params(req)?;
        let product_2 = req.ctx.build(Product::from_attributes(&attributes)?);
        req.ctx.save_bang(product_2)?;
        let product = product_2;
        Ok(Response::json(
            status::CREATED,
            AsJson::<Product>::new().render(&mut req.ctx, product)?,
        ))
    }

    // app/controllers/products_controller.rb:17
    pub fn update(&mut self, req: &mut Request) -> Result<Response> {
        let product = self.product.ok_or(Error::Nil { what: "update!" })?;
        let attributes = self.product_params(req)?;
        req.ctx.assign(product, &attributes)?;
        req.ctx.save_bang(product)?;
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_option(&mut req.ctx, self.product)?,
        ))
    }

    // app/controllers/products_controller.rb:22
    pub fn restock(&mut self, req: &mut Request) -> Result<Response> {
        let amount = req.params.fetch("amount", 0).to_i()?;
        let amount_2 = self.amount(req, amount)?;
        Product::restock_bang(
            &mut req.ctx,
            self.product.ok_or(Error::Nil { what: "restock!" })?,
            amount_2,
        )?;
        Ok(Response::json(
            status::OK,
            AsJson::<Product>::new().render_option(&mut req.ctx, self.product)?,
        ))
    }

    // app/controllers/products_controller.rb:27
    pub fn quote(&mut self, req: &mut Request) -> Result<Response> {
        let quantity_2 = req.params.fetch("quantity", 1).to_i()?;
        let quantity = self.amount(req, quantity_2)?;
        let id = req.ctx[self.product.ok_or(Error::Nil { what: "id" })?].id;
        let price_for = Product::price_for(
            &mut req.ctx,
            self.product.ok_or(Error::Nil { what: "price_for" })?,
            quantity,
        )?;
        Ok(Response::json(
            status::OK,
            json!({ "product_id": id, "quantity": quantity, "total_cents": price_for, "in_stock": Product::is_in_stock(&mut req.ctx, self.product.ok_or(Error::Nil { what: "in_stock?" })?, quantity)? }),
        ))
    }

    // app/controllers/products_controller.rb:35
    fn set_product(&mut self, req: &mut Request) -> Result<()> {
        self.product = Some(Product::find(&mut req.ctx, req.params.value("id"))?);
        Ok(())
    }

    // app/controllers/products_controller.rb:39
    fn product_params(&mut self, req: &mut Request) -> Result<Attributes> {
        Ok(req
            .params
            .expect("product", &["name", "price_cents", "stock", "active"])?)
    }

    // app/controllers/products_controller.rb:45
    fn amount(&mut self, _req: &mut Request, requested: i64) -> Result<i64> {
        Ok(i64::max(requested, 0))
    }
}
