//! Generated by Rutile from app/controllers/storefront_controller.rb. Edit the Ruby, not this file.

use rustonrails::{
    Controller, Error, Handle, Model, Relation, Request, Response, Result, View, html_escape,
    link_to,
};

use crate::models::{Product, ProductScopes};

// app/controllers/storefront_controller.rb:3
#[derive(Default)]
pub struct StorefrontController {
    product: Option<Handle<Product>>,
    products: Option<Relation<Product>>,
    related: Option<Relation<Product>>,
}

impl Controller for StorefrontController {
    fn wrap_parameters() -> Option<(&'static str, Option<&'static [&'static str]>)> {
        Some(("storefront", None))
    }

    fn before(&mut self, req: &mut Request, action: &str) -> Result<Option<Response>> {
        // verify_authenticity_token: Rails' forgery protection, which lets GET through
        // verify_same_origin_request: Rails' forgery protection, which lets GET through
        // before_action :set_product
        if matches!(action, "show") {
            self.set_product(req)?;
        }
        Ok(None)
    }
}

impl StorefrontController {
    // app/controllers/storefront_controller.rb:6
    pub fn index(&mut self, req: &mut Request) -> Result<Response> {
        self.products = Some(Product::all().available().order_asc("name"));
        self.render_storefront_index(req, 200, Some("index"))
    }

    // app/controllers/storefront_controller.rb:10
    pub fn show(&mut self, req: &mut Request) -> Result<Response> {
        self.related = Some(
            Product::all()
                .available()
                .where_not(
                    "id",
                    req.ctx[self.product.ok_or(Error::Nil { what: "id" })?].id,
                )
                .order_asc("name")
                .limit(2),
        );
        self.render_storefront_show(req, 200, Some("show"))
    }

    // app/controllers/storefront_controller.rb:16
    fn set_product(&mut self, req: &mut Request) -> Result<()> {
        self.product = Some(Product::find(&mut req.ctx, req.params.value("id")?)?);
        Ok(())
    }

    fn render_storefront_index(
        &mut self,
        req: &mut Request,
        status: u16,
        implicit: Option<&str>,
    ) -> Result<Response> {
        View::negotiate(req, "StorefrontController", "storefront/index", implicit)?;
        let mut view = View::default();
        self.view_storefront_index(req, &mut view)?;
        view.lay_out();
        self.view_layouts_storefront(req, &mut view)?;
        Ok(view.response(status))
    }

    fn render_storefront_show(
        &mut self,
        req: &mut Request,
        status: u16,
        implicit: Option<&str>,
    ) -> Result<Response> {
        View::negotiate(req, "StorefrontController", "storefront/show", implicit)?;
        let mut view = View::default();
        self.view_storefront_show(req, &mut view)?;
        view.lay_out();
        self.view_layouts_storefront(req, &mut view)?;
        Ok(view.response(status))
    }

    // app/views/storefront/index.html.erb
    fn view_storefront_index(&mut self, req: &mut Request, view: &mut View) -> Result<()> {
        view.content_for_append("title", &"Everything in stock");
        view.text("<h1>In stock</h1>\n");
        if self
            .products
            .clone()
            .ok_or(Error::Nil { what: "any?" })?
            .is_any(&mut req.ctx)?
        {
            view.text("  <ul>\n");
            let records = self
                .products
                .clone()
                .ok_or(Error::Nil { what: "each" })?
                .load(&mut req.ctx)?;
            for product in records {
                view.text("    <li>");
                view.raw(&link_to(
                    req.ctx[product]
                        .name
                        .clone()
                        .as_deref()
                        .map(html_escape)
                        .as_deref(),
                    &crate::routes::shop_product_path(req.ctx[product].id)?,
                    &[],
                ));
                view.text(": ");
                view.append(
                    &req.ctx[product]
                        .stock
                        .map(|value| value.to_string())
                        .unwrap_or_default(),
                );
                view.text(" left</li>\n");
            }
            view.text("  </ul>\n");
        } else {
            view.text("  <p>Sold out &mdash; come back soon.</p>\n");
        }
        Ok(())
    }

    // app/views/storefront/show.html.erb
    fn view_storefront_show(&mut self, req: &mut Request, view: &mut View) -> Result<()> {
        view.content_for_append(
            "title",
            &html_escape(
                req.ctx[self.product.ok_or(Error::Nil { what: "name" })?]
                    .name
                    .clone()
                    .as_deref()
                    .unwrap_or_default(),
            ),
        );
        view.text("<h1>");
        view.append(
            req.ctx[self.product.ok_or(Error::Nil { what: "name" })?]
                .name
                .clone()
                .as_deref()
                .unwrap_or_default(),
        );
        view.text("</h1>\n<p class=\"price\">");
        view.append(
            &req.ctx[self.product.ok_or(Error::Nil {
                what: "price_cents",
            })?]
            .price_cents
            .map(|value| value.to_string())
            .unwrap_or_default(),
        );
        view.text(" cents</p>\n");
        if Product::is_in_stock(
            &mut req.ctx,
            self.product.ok_or(Error::Nil { what: "in_stock?" })?,
            1,
        )? {
            view.text("  <p>");
            view.append(
                &req.ctx[self.product.ok_or(Error::Nil { what: "stock" })?]
                    .stock
                    .map(|value| value.to_string())
                    .unwrap_or_default(),
            );
            view.text(" in stock</p>\n");
        } else {
            view.text("  <p class=\"out\">Not available</p>\n");
        }
        if self
            .related
            .clone()
            .ok_or(Error::Nil { what: "any?" })?
            .is_any(&mut req.ctx)?
        {
            view.text("  <h2>Also available</h2>\n");
            let records = self
                .related
                .clone()
                .ok_or(Error::Nil { what: "each" })?
                .load(&mut req.ctx)?;
            for other in records {
                view.text("    ");
                view.raw(&link_to(
                    req.ctx[other]
                        .name
                        .clone()
                        .as_deref()
                        .map(html_escape)
                        .as_deref(),
                    &crate::routes::shop_product_path(req.ctx[other].id)?,
                    &[("class", "related")],
                ));
                view.text("\n");
            }
        }
        Ok(())
    }

    // app/views/layouts/storefront.html.erb
    fn view_layouts_storefront(&mut self, _req: &mut Request, view: &mut View) -> Result<()> {
        view.text("<!DOCTYPE html>\n<html>\n  <head>\n    <title>");
        view.raw(
            &view
                .content_for("title")
                .unwrap_or_else(|| "The Store".to_string()),
        );
        view.text("</title>\n  </head>\n  <body>\n    <header>");
        view.raw(&link_to(
            Some(&"The Store"),
            &crate::routes::shop_path()?,
            &[],
        ));
        view.text("</header>\n    <main>\n");
        view.append_content();
        view.text("\n    </main>\n    <footer>Prices in cents — stock as of this page</footer>\n  </body>\n</html>\n");
        Ok(())
    }
}
