//! Generated by Rutile from app/models/membership.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{Behavior, BelongsTo, Check, Model, Relation, Time, model};

use super::{Project, User};

// app/models/membership.rb:1
model! {
pub struct Membership in "memberships" {
id: i64,
user_id: i64,
project_id: i64,
role: String = "member",
created_at: Time,
updated_at: Time,
}
}

impl Membership {
    // belongs_to :user
    pub const USER: BelongsTo<Membership, User> = BelongsTo::new("user", "user_id");

    // belongs_to :project
    pub const PROJECT: BelongsTo<Membership, Project> = BelongsTo::new("project", "project_id");

    // enum :role
    pub fn is_member(&self) -> bool {
        self.role.as_deref() == Some("member")
    }

    pub fn is_admin(&self) -> bool {
        self.role.as_deref() == Some("admin")
    }
}

impl Model for Membership {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Membership>> = LazyLock::new(|| {
            Behavior::<Membership>::new()
                // belongs_to :user
                .belongs_to(&Membership::USER)
                // belongs_to :project
                .belongs_to(&Membership::PROJECT)
                // enum :role
                .enumeration("role", &[("member", 0), ("admin", 1)], true)
                // validates :user_id, uniqueness
                .validates(
                    "user_id",
                    Check::Uniqueness {
                        scope: &["project_id"],
                    },
                )
        });
        &BEHAVIOR
    }
}

pub trait MembershipScopes {
    fn admin(self) -> Self;
    fn member(self) -> Self;
    fn not_admin(self) -> Self;
    fn not_member(self) -> Self;
}

impl MembershipScopes for Relation<Membership> {
    fn admin(self) -> Self {
        self.where_eq("role", "admin")
    }

    fn member(self) -> Self {
        self.where_eq("role", "member")
    }

    fn not_admin(self) -> Self {
        self.where_not("role", "admin")
    }

    fn not_member(self) -> Self {
        self.where_not("role", "member")
    }
}
