//! Generated by Rutile from app/models/project.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{
    Behavior, BelongsTo, Check, Ctx, Handle, HasMany, HasManyThrough, Model, Record, Relation,
    Result, Time, Value, model, now,
};

use super::{Membership, Task, User};

// app/models/project.rb:1
model! {
pub struct Project in "projects" {
id: i64,
name: String,
owner_id: i64,
archived_at: Time,
created_at: Time,
updated_at: Time,
}
}

impl Project {
    // belongs_to :owner
    pub const OWNER: BelongsTo<Project, User> = BelongsTo::new("owner", "owner_id");

    // has_many :memberships
    pub const MEMBERSHIPS: HasMany<Project, Membership> =
        HasMany::new("memberships", "project_id", Some(&Membership::PROJECT));

    // has_many :members, through: :memberships
    pub const MEMBERS: HasManyThrough<Project, User> =
        HasManyThrough::new("members", "memberships", "project_id", "user_id");

    // has_many :tasks
    pub const TASKS: HasMany<Project, Task> =
        HasMany::new("tasks", "project_id", Some(&Task::PROJECT));

    // app/models/project.rb:21
    fn add_owner_as_admin(ctx: &mut Ctx, project: Handle<Project>) -> Result<()> {
        let membership = Project::MEMBERSHIPS.build(ctx, project, Membership::new_record())?;
        let owner = Project::OWNER.get(ctx, project)?;
        if let Some(owner) = owner {
            Membership::USER.set(ctx, membership, owner)?;
        } else {
            ctx[membership].user_id = None;
        }
        ctx[membership].role = Some("admin".to_string());
        ctx.save_bang(membership)?;
        Ok(())
    }

    // app/models/project.rb:13
    pub fn is_archived(ctx: &mut Ctx, project: Handle<Project>) -> Result<bool> {
        Ok(ctx[project].archived_at.is_some())
    }

    // app/models/project.rb:15
    pub fn archive_bang(ctx: &mut Ctx, project: Handle<Project>) -> Result<()> {
        ctx[project].archived_at = Some(now());
        Ok(ctx.save_bang(project)?)
    }
}

impl Model for Project {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Project>> = LazyLock::new(|| {
            Behavior::<Project>::new()
                // belongs_to :owner
                .belongs_to(&Project::OWNER)
                // validates :name, presence
                .validates("name", Check::Presence)
                // validates :name, length
                .validates(
                    "name",
                    Check::Length {
                        minimum: None,
                        maximum: Some(100),
                    },
                )
                // validates :name, uniqueness
                .validates(
                    "name",
                    Check::Uniqueness {
                        scope: &["owner_id"],
                    },
                )
                // after_create :add_owner_as_admin (app/models/project.rb:21)
                .after_create(Project::add_owner_as_admin)
                // has_many :memberships, dependent: :destroy
                .before_destroy(|ctx, project| Project::MEMBERSHIPS.destroy_all(ctx, project))
                // has_many :tasks, dependent: :destroy
                .before_destroy(|ctx, project| Project::TASKS.destroy_all(ctx, project))
        });
        &BEHAVIOR
    }
}

pub trait ProjectScopes {
    fn active(self) -> Self;
}

impl ProjectScopes for Relation<Project> {
    // app/models/project.rb:9
    fn active(self) -> Self {
        self.where_eq("archived_at", Value::Nil)
    }
}
