//! Generated by Rutile from app/models/task.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{
    Behavior, BelongsTo, Check, Ctx, Date, Error, Handle, Model, Number, Numericality, Relation,
    Result, Time, model, now, sanitize_sql_like, today,
};

use super::{Project, User};

// app/models/task.rb:1
model! {
pub struct Task in "tasks" {
id: i64,
project_id: i64,
assignee_id: i64,
title: String,
notes: String,
status: String = "todo",
priority: String = "normal",
estimate: i64,
due_on: Date,
completed_at: Time,
created_at: Time,
updated_at: Time,
}
}

impl Task {
    // belongs_to :project
    pub const PROJECT: BelongsTo<Task, Project> = BelongsTo::new("project", "project_id");

    // belongs_to :assignee
    pub const ASSIGNEE: BelongsTo<Task, User> = BelongsTo::new("assignee", "assignee_id");

    // enum :priority
    pub fn is_low(&self) -> bool {
        self.priority.as_deref() == Some("low")
    }

    pub fn is_normal(&self) -> bool {
        self.priority.as_deref() == Some("normal")
    }

    pub fn is_high(&self) -> bool {
        self.priority.as_deref() == Some("high")
    }

    // enum :status
    pub fn is_todo(&self) -> bool {
        self.status.as_deref() == Some("todo")
    }

    pub fn is_doing(&self) -> bool {
        self.status.as_deref() == Some("doing")
    }

    pub fn is_done(&self) -> bool {
        self.status.as_deref() == Some("done")
    }

    // app/models/task.rb:23
    fn assignee_is_a_member(ctx: &mut Ctx, task: Handle<Task>) -> Result<()> {
        if Task::ASSIGNEE.get(ctx, task)?.is_none() || Task::PROJECT.get(ctx, task)?.is_none() {
            return Ok(());
        }
        let project = Task::PROJECT
            .get(ctx, task)?
            .ok_or(Error::Nil { what: "members" })?;
        let assignee = Task::ASSIGNEE.get(ctx, task)?;
        if !(Project::MEMBERS.of(ctx, project).contains(ctx, assignee)?) {
            ctx.errors_mut(task)
                .add("assignee", "must be a member of the project");
        }
        Ok(())
    }

    // app/models/task.rb:29
    fn stamp_completion(ctx: &mut Ctx, task: Handle<Task>) -> Result<()> {
        let value = if ctx[task].is_done() {
            Some(now())
        } else {
            None
        };
        ctx[task].completed_at = value;
        Ok(())
    }

    // app/models/task.rb:17
    pub fn is_overdue(ctx: &mut Ctx, task: Handle<Task>) -> Result<bool> {
        Ok((ctx[task].due_on.is_some()
            && ctx[task].due_on.ok_or(Error::Nil { what: "<" })? < today())
            && !(ctx[task].is_done()))
    }
}

impl Model for Task {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Task>> = LazyLock::new(|| {
            Behavior::<Task>::new()
                // belongs_to :project
                .belongs_to(&Task::PROJECT)
                // enum :status
                .enumeration("status", &[("todo", 0), ("doing", 1), ("done", 2)], true)
                // enum :priority
                .enumeration("priority", &[("low", 0), ("normal", 1), ("high", 2)], true)
                // validates :title, presence
                .validates("title", Check::Presence)
                // validates :title, length
                .validates(
                    "title",
                    Check::Length {
                        minimum: None,
                        maximum: Some(200),
                    },
                )
                // validates :estimate, numericality
                .validates(
                    "estimate",
                    Check::Numericality(Numericality {
                        only_integer: true,
                        greater_than: Some(Number::Int(0)),
                        ..Numericality::default()
                    }),
                )
                .allow_nil()
                // validate :assignee_is_a_member (app/models/task.rb:23)
                .validate(Task::assignee_is_a_member)
                // before_save :stamp_completion (app/models/task.rb:29)
                .before_save(Task::stamp_completion)
                .when(|ctx, task| ctx.attribute_changed(task, "status"))
        });
        &BEHAVIOR
    }
}

pub trait TaskScopes {
    fn doing(self) -> Self;
    fn done(self) -> Self;
    fn high(self) -> Self;
    fn low(self) -> Self;
    fn normal(self) -> Self;
    fn not_doing(self) -> Self;
    fn not_done(self) -> Self;
    fn not_high(self) -> Self;
    fn not_low(self) -> Self;
    fn not_normal(self) -> Self;
    fn not_todo(self) -> Self;
    fn search(self, query: String) -> Self;
    fn todo(self) -> Self;
    fn unfinished(self) -> Self;
}

impl TaskScopes for Relation<Task> {
    fn doing(self) -> Self {
        self.where_eq("status", "doing")
    }

    fn done(self) -> Self {
        self.where_eq("status", "done")
    }

    fn high(self) -> Self {
        self.where_eq("priority", "high")
    }

    fn low(self) -> Self {
        self.where_eq("priority", "low")
    }

    fn normal(self) -> Self {
        self.where_eq("priority", "normal")
    }

    fn not_doing(self) -> Self {
        self.where_not("status", "doing")
    }

    fn not_done(self) -> Self {
        self.where_not("status", "done")
    }

    fn not_high(self) -> Self {
        self.where_not("priority", "high")
    }

    fn not_low(self) -> Self {
        self.where_not("priority", "low")
    }

    fn not_normal(self) -> Self {
        self.where_not("priority", "normal")
    }

    fn not_todo(self) -> Self {
        self.where_not("status", "todo")
    }

    // app/models/task.rb:13
    fn search(self, query: String) -> Self {
        self.where_sql(
            "title ILIKE ?",
            vec![format!("%{}%", sanitize_sql_like(&query)).into()],
        )
    }

    fn todo(self) -> Self {
        self.where_eq("status", "todo")
    }

    // app/models/task.rb:12
    fn unfinished(self) -> Self {
        self.where_not("status", "done")
    }
}
