//! Generated by Rutile from app/models/user.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{Behavior, Check, HasMany, HasManyThrough, Model, RubyString, Time, model};

use super::{Membership, Project, Task};

// app/models/user.rb:1
model! {
pub struct User in "users" {
id: i64,
name: String,
email: String,
api_token: String,
created_at: Time,
updated_at: Time,
}
}

impl User {
    // has_many :memberships
    pub const MEMBERSHIPS: HasMany<User, Membership> =
        HasMany::new("memberships", "user_id", Some(&Membership::USER));

    // has_many :projects, through: :memberships
    pub const PROJECTS: HasManyThrough<User, Project> =
        HasManyThrough::new("projects", "memberships", "user_id", "project_id");

    // has_many :owned_projects
    pub const OWNED_PROJECTS: HasMany<User, Project> =
        HasMany::new("owned_projects", "owner_id", Some(&Project::OWNER));

    // has_many :assigned_tasks
    pub const ASSIGNED_TASKS: HasMany<User, Task> =
        HasMany::new("assigned_tasks", "assignee_id", Some(&Task::ASSIGNEE));

    // normalizes :email (app/models/user.rb:8)
    pub fn normalize_email(email: String) -> String {
        email.strip().downcase()
    }
}

impl Model for User {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<User>> = LazyLock::new(|| {
            Behavior::<User>::new()
                // normalizes :email
                .normalizes("email", User::normalize_email)
                // has_secure_token :api_token
                .has_secure_token("api_token", 24)
                // validates :name, presence
                .validates("name", Check::Presence)
                // validates :email, presence
                .validates("email", Check::Presence)
                // validates :email, uniqueness
                .validates("email", Check::Uniqueness { scope: &[] })
                // has_many :memberships, dependent: :destroy
                .before_destroy(|ctx, user| User::MEMBERSHIPS.destroy_all(ctx, user))
                // has_many :owned_projects, dependent: :destroy
                .before_destroy(|ctx, user| User::OWNED_PROJECTS.destroy_all(ctx, user))
                // has_many :assigned_tasks, dependent: :nullify
                .before_destroy(|ctx, user| User::ASSIGNED_TASKS.nullify_all(ctx, user))
        });
        &BEHAVIOR
    }
}
