//! Generated by Rutile from app/models/application_record.rb. Edit the Ruby, not this file.

use rustonrails::{Model, Relation, Time};

pub trait ApplicationRecordScopes {
    fn created_since(self, time: Time) -> Self;
}

impl<M: Model> ApplicationRecordScopes for Relation<M> {
    // app/models/application_record.rb:4
    fn created_since(self, time: Time) -> Self {
        self.where_gte("created_at", time)
    }
}
