//! Generated by Rutile from app/models/comment.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{Behavior, BelongsTo, Check, Ctx, Error, Handle, Model, Result, Time, model};

use super::{Post, User};

// app/models/comment.rb:1
model! {
pub struct Comment in "comments" {
id: i64,
post_id: i64,
user_id: i64,
body: String,
created_at: Time,
updated_at: Time,
}
}

impl Comment {
    // belongs_to :post
    pub const POST: BelongsTo<Comment, Post> = BelongsTo::new("post", "post_id");

    // belongs_to :user
    pub const USER: BelongsTo<Comment, User> = BelongsTo::new("user", "user_id");

    // app/models/comment.rb:12
    fn post_is_published(ctx: &mut Ctx, comment: Handle<Comment>) -> Result<()> {
        let post = Comment::POST.get(ctx, comment)?;
        if post.is_some_and(|post| ctx[post].is_draft()) {
            ctx.errors_mut(comment).add("post", "must be published");
        }
        Ok(())
    }

    // app/models/comment.rb:16
    fn bump_post_counter(ctx: &mut Ctx, comment: Handle<Comment>) -> Result<()> {
        let post = Comment::POST
            .get(ctx, comment)?
            .ok_or(Error::Nil { what: "increment!" })?;
        ctx.increment_bang(post, "comments_count", 1)?;
        Ok(())
    }
}

impl Model for Comment {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Comment>> = LazyLock::new(|| {
            Behavior::<Comment>::new()
                // belongs_to :post
                .belongs_to(&Comment::POST)
                // belongs_to :user
                .belongs_to(&Comment::USER)
                // validates :body, presence
                .validates("body", Check::Presence)
                // validates :body, length
                .validates(
                    "body",
                    Check::Length {
                        minimum: None,
                        maximum: Some(2000),
                    },
                )
                // validate :post_is_published (app/models/comment.rb:12)
                .validate(Comment::post_is_published)
                // after_create :bump_post_counter (app/models/comment.rb:16)
                .after_create(Comment::bump_post_counter)
        });
        &BEHAVIOR
    }
}
