//! Generated by Rutile from app/models. Edit the Ruby, not this file.

mod application_record;
mod comment;
mod post;
mod user;

pub use application_record::ApplicationRecordScopes;
pub use comment::Comment;
pub use post::{Post, PostScopes};
pub use user::User;
