//! Generated by Rutile from app/models/post.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{
    Behavior, BelongsTo, Check, Ctx, Handle, HasMany, Model, Relation, Result, Time, model, now,
};

use super::{Comment, User};

// app/models/post.rb:1
model! {
pub struct Post in "posts" {
id: i64,
user_id: i64,
title: String,
body: String,
status: String = "draft",
published_at: Time,
comments_count: i64 = 0,
created_at: Time,
updated_at: Time,
}
}

impl Post {
    // belongs_to :user
    pub const USER: BelongsTo<Post, User> = BelongsTo::new("user", "user_id");

    // has_many :comments
    pub const COMMENTS: HasMany<Post, Comment> =
        HasMany::new("comments", "post_id", Some(&Comment::POST));

    // enum :status
    pub fn is_draft(&self) -> bool {
        self.status.as_deref() == Some("draft")
    }

    pub fn is_published(&self) -> bool {
        self.status.as_deref() == Some("published")
    }

    // app/models/post.rb:16
    fn stamp_published_at(ctx: &mut Ctx, post: Handle<Post>) -> Result<()> {
        if ctx[post].published_at.is_none() {
            ctx[post].published_at = Some(now());
        }
        Ok(())
    }
}

impl Model for Post {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<Post>> = LazyLock::new(|| {
            Behavior::<Post>::new()
                // belongs_to :user
                .belongs_to(&Post::USER)
                // enum :status
                .enumeration("status", &[("draft", 0), ("published", 1)], true)
                // validates :title, presence
                .validates("title", Check::Presence)
                // validates :title, length
                .validates(
                    "title",
                    Check::Length {
                        minimum: None,
                        maximum: Some(200),
                    },
                )
                // before_save :stamp_published_at (app/models/post.rb:16)
                .before_save(Post::stamp_published_at)
                .when(|ctx, post| ctx[post].is_published())
                // has_many :comments, dependent: :destroy
                .before_destroy(|ctx, post| Post::COMMENTS.destroy_all(ctx, post))
        });
        &BEHAVIOR
    }
}

pub trait PostScopes {
    fn draft(self) -> Self;
    fn not_draft(self) -> Self;
    fn not_published(self) -> Self;
    fn published(self) -> Self;
    fn recent(self) -> Self;
    fn visible(self) -> Self;
}

impl PostScopes for Relation<Post> {
    fn draft(self) -> Self {
        self.where_eq("status", "draft")
    }

    fn not_draft(self) -> Self {
        self.where_not("status", "draft")
    }

    fn not_published(self) -> Self {
        self.where_not("status", "published")
    }

    fn published(self) -> Self {
        self.where_eq("status", "published")
    }

    // app/models/post.rb:9
    fn recent(self) -> Self {
        self.order_desc("created_at")
    }

    // app/models/post.rb:10
    fn visible(self) -> Self {
        self.where_eq("status", "published")
    }
}
