//! Generated by Rutile from app/models/user.rb. Edit the Ruby, not this file.

use std::sync::LazyLock;

use rustonrails::{Behavior, Check, HasMany, Model, Regex, RubyString, Time, model};

use super::{Comment, Post};

// app/models/user.rb:1
model! {
pub struct User in "users" {
id: i64,
name: String,
email: String,
created_at: Time,
updated_at: Time,
}
}

impl User {
    // has_many :posts
    pub const POSTS: HasMany<User, Post> = HasMany::new("posts", "user_id", Some(&Post::USER));

    // has_many :comments
    pub const COMMENTS: HasMany<User, Comment> =
        HasMany::new("comments", "user_id", Some(&Comment::USER));
}

impl Model for User {
    fn behavior() -> &'static Behavior<Self> {
        static BEHAVIOR: LazyLock<Behavior<User>> = LazyLock::new(|| {
            Behavior::<User>::new()
// validates :name, presence
.validates("name", Check::Presence)
// validates :email, presence
.validates("email", Check::Presence)
// validates :email, uniqueness
.validates("email", Check::Uniqueness)
// validates :email, format
.validates("email", Check::Format(Regex::new(r"\A[a-zA-Z0-9.!\#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\z").expect("the Ruby regexp compiles")))
// before_validation (app/models/user.rb:5)
.before_validation(|ctx, user| {
let email = ctx[user].email.clone().unwrap_or_default().strip().downcase();
ctx[user].email = Some(email);
Ok(())
})
// has_many :posts, dependent: :destroy
.before_destroy(|ctx, user| User::POSTS.destroy_all(ctx, user))
// has_many :comments, dependent: :destroy
.before_destroy(|ctx, user| User::COMMENTS.destroy_all(ctx, user))
        });
        &BEHAVIOR
    }
}
