//! RustOnRails: the Rails API surface in Rust.
//!
//! This is the runtime that code generated by Rutile links against. See
//! `docs/design.md` for the memory model and the planned modules. Nothing is
//! implemented yet.
