//! RustOnRails: the Rails API surface in Rust.
//!
//! This is the runtime that code generated by Rutile links against. The
//! record layer mirrors Active Record: models are plain structs, a `Ctx`
//! owns the database connection and every record one unit of work touches,
//! and code refers to records through `Handle`s. See `docs/design.md`.

mod association;
mod behavior;
mod cast;
mod ctx;
mod enums;
mod error;
mod http;
mod json;
mod model;
mod normalization;
mod numericality;
mod persistence;
mod pg;
mod records;
mod relation;
mod secure_token;
mod support;
pub mod testing;
mod transaction;
mod validation;
mod value;
mod write;

pub use association::{BelongsTo, HasMany, HasManyThrough, Preload};
pub use behavior::{Behavior, Check, Cond, Event, Hook, Normalizer};
pub use cast::FromValue;
pub use ctx::{Connection, Ctx};
pub use error::{Error, RecordInvalid, Result};
pub use http::{Action, Constraint, Controller, Handler, Params, Request, Response, Router, action, error_page, error_response, health, parse_query, reason, status};
pub use http::server;
pub use json::{AsJson, errors_json, format_date, format_time, merge, value_json};
pub use records::Handle;
pub use model::{Attributes, Model, Record};
#[doc(hidden)]
pub use model::BeforeTypeCast;
pub use numericality::{Number, Numericality};
pub use relation::{Batches, InnerJoin, Joinable, Relation, sanitize_sql_like};
pub use secure_token::base58;
pub use support::{Blank, RubyString, sum_integers};
pub use validation::Errors;
pub use value::{Date, Time, Value, local_today, now, today};
pub use serde_json::{Value as Json, json};
pub use regex::Regex;
