//! Generated by Rutile from config/routes.rb. Edit the Ruby, not this file.

use rustonrails::{Result, Router, ToParam, action, health, path_segment};

use crate::controllers::{ProjectsController, TasksController, UsersController};

/// config/routes.rb, in the order Rails matches it.
pub fn routes() -> Router {
    Router::new()
        .default_headers(&[
            ("X-Frame-Options", "SAMEORIGIN"),
            ("X-XSS-Protection", "0"),
            ("X-Content-Type-Options", "nosniff"),
            ("X-Permitted-Cross-Domain-Policies", "none"),
            ("Referrer-Policy", "strict-origin-when-cross-origin"),
        ])
        // POST /users(.:format) users#create
        .post(
            "/users(.:format)",
            action("create", UsersController::create),
        )
        // GET /users/:id(.:format) users#show
        .get(
            "/users/:id(.:format)",
            action("show", UsersController::show),
        )
        // POST /projects/:id/archive(.:format) projects#archive
        .post(
            "/projects/:id/archive(.:format)",
            action("archive", ProjectsController::archive),
        )
        // PATCH /tasks/:id/complete(.:format) tasks#complete
        .patch(
            "/tasks/:id/complete(.:format)",
            action("complete", TasksController::complete),
        )
        // GET /projects/:project_id/tasks(.:format) tasks#index
        .get(
            "/projects/:project_id/tasks(.:format)",
            action("index", TasksController::index),
        )
        // POST /projects/:project_id/tasks(.:format) tasks#create
        .post(
            "/projects/:project_id/tasks(.:format)",
            action("create", TasksController::create),
        )
        // GET /tasks/:id(.:format) tasks#show
        .get(
            "/tasks/:id(.:format)",
            action("show", TasksController::show),
        )
        // PATCH /tasks/:id(.:format) tasks#update
        .patch(
            "/tasks/:id(.:format)",
            action("update", TasksController::update),
        )
        // PUT /tasks/:id(.:format) tasks#update
        .put(
            "/tasks/:id(.:format)",
            action("update", TasksController::update),
        )
        // DELETE /tasks/:id(.:format) tasks#destroy
        .delete(
            "/tasks/:id(.:format)",
            action("destroy", TasksController::destroy),
        )
        // GET /projects(.:format) projects#index
        .get(
            "/projects(.:format)",
            action("index", ProjectsController::index),
        )
        // POST /projects(.:format) projects#create
        .post(
            "/projects(.:format)",
            action("create", ProjectsController::create),
        )
        // GET /projects/:id(.:format) projects#show
        .get(
            "/projects/:id(.:format)",
            action("show", ProjectsController::show),
        )
        // PATCH /projects/:id(.:format) projects#update
        .patch(
            "/projects/:id(.:format)",
            action("update", ProjectsController::update),
        )
        // PUT /projects/:id(.:format) projects#update
        .put(
            "/projects/:id(.:format)",
            action("update", ProjectsController::update),
        )
        // DELETE /projects/:id(.:format) projects#destroy
        .delete(
            "/projects/:id(.:format)",
            action("destroy", ProjectsController::destroy),
        )
        // GET /up(.:format) rails/health#show
        .get("/up(.:format)", Box::new(health))
}

/// `users_path`: /users(.:format)
pub fn users_path() -> Result<String> {
    Ok("/users".to_string())
}

/// `user_path`: /users/:id(.:format)
pub fn user_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/users/{}",
        path_segment(id, "users", "show", "id")?
    ))
}

/// `archive_project_path`: /projects/:id/archive(.:format)
pub fn archive_project_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/projects/{}/archive",
        path_segment(id, "projects", "archive", "id")?
    ))
}

/// `complete_task_path`: /tasks/:id/complete(.:format)
pub fn complete_task_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/tasks/{}/complete",
        path_segment(id, "tasks", "complete", "id")?
    ))
}

/// `project_tasks_path`: /projects/:project_id/tasks(.:format)
pub fn project_tasks_path(project_id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/projects/{}/tasks",
        path_segment(project_id, "tasks", "index", "project_id")?
    ))
}

/// `task_path`: /tasks/:id(.:format)
pub fn task_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/tasks/{}",
        path_segment(id, "tasks", "show", "id")?
    ))
}

/// `projects_path`: /projects(.:format)
pub fn projects_path() -> Result<String> {
    Ok("/projects".to_string())
}

/// `project_path`: /projects/:id(.:format)
pub fn project_path(id: impl ToParam) -> Result<String> {
    Ok(format!(
        "/projects/{}",
        path_segment(id, "projects", "show", "id")?
    ))
}

/// `rails_health_check_path`: /up(.:format)
pub fn rails_health_check_path() -> Result<String> {
    Ok("/up".to_string())
}
