//! Generated by Rutile from config/routes.rb. Edit the Ruby, not this file.

use rustonrails::{Router, action, health};

use crate::controllers::{ProjectsController, TasksController, UsersController};

/// config/routes.rb, in the order Rails matches it.
pub fn routes() -> Router {
    Router::new()
        // POST /users(.:format) users#create
        .post(
            "/users(.:format)",
            action("create", UsersController::create),
        )
        // GET /users/:id(.:format) users#show
        .get(
            "/users/:id(.:format)",
            action("show", UsersController::show),
        )
        // POST /projects/:id/archive(.:format) projects#archive
        .post(
            "/projects/:id/archive(.:format)",
            action("archive", ProjectsController::archive),
        )
        // PATCH /tasks/:id/complete(.:format) tasks#complete
        .patch(
            "/tasks/:id/complete(.:format)",
            action("complete", TasksController::complete),
        )
        // GET /projects/:project_id/tasks(.:format) tasks#index
        .get(
            "/projects/:project_id/tasks(.:format)",
            action("index", TasksController::index),
        )
        // POST /projects/:project_id/tasks(.:format) tasks#create
        .post(
            "/projects/:project_id/tasks(.:format)",
            action("create", TasksController::create),
        )
        // GET /tasks/:id(.:format) tasks#show
        .get(
            "/tasks/:id(.:format)",
            action("show", TasksController::show),
        )
        // PATCH /tasks/:id(.:format) tasks#update
        .patch(
            "/tasks/:id(.:format)",
            action("update", TasksController::update),
        )
        // PUT /tasks/:id(.:format) tasks#update
        .put(
            "/tasks/:id(.:format)",
            action("update", TasksController::update),
        )
        // DELETE /tasks/:id(.:format) tasks#destroy
        .delete(
            "/tasks/:id(.:format)",
            action("destroy", TasksController::destroy),
        )
        // GET /projects(.:format) projects#index
        .get(
            "/projects(.:format)",
            action("index", ProjectsController::index),
        )
        // POST /projects(.:format) projects#create
        .post(
            "/projects(.:format)",
            action("create", ProjectsController::create),
        )
        // GET /projects/:id(.:format) projects#show
        .get(
            "/projects/:id(.:format)",
            action("show", ProjectsController::show),
        )
        // PATCH /projects/:id(.:format) projects#update
        .patch(
            "/projects/:id(.:format)",
            action("update", ProjectsController::update),
        )
        // PUT /projects/:id(.:format) projects#update
        .put(
            "/projects/:id(.:format)",
            action("update", ProjectsController::update),
        )
        // DELETE /projects/:id(.:format) projects#destroy
        .delete(
            "/projects/:id(.:format)",
            action("destroy", ProjectsController::destroy),
        )
        // GET /up(.:format) rails/health#show
        .get("/up(.:format)", Box::new(health))
}
